const express = require("express");

function createInboxRouter({ store, repository, events, requireAuth, remoteDesktopConfig }) {
  const router = express.Router();
  router.use(requireAuth);
  const workspaceIds = (req) => store.listWorkspaces(req.user).map((workspace) => workspace.id);
  const fail = (res, error) => res.status(error.message === "Invalid pagination cursor" ? 400 : 500).json({ error: error.message });

  router.get("/conversations", async (req,res) => { try { res.json(await repository.listConversations({ ...req.query, workspaceIds: workspaceIds(req) })); } catch(error) { fail(res,error); } });
  router.get("/conversations/:id/messages", async (req,res) => { try { const result=await repository.listMessages(workspaceIds(req),req.params.id,req.query); if(!result)return res.status(404).json({error:"Conversation not found"}); res.json(result); } catch(error){ fail(res,error); } });
  router.post("/conversations/:id/read", async (req,res) => { try { const c=await repository.markRead(workspaceIds(req),req.params.id); if(!c)return res.status(404).json({error:"Conversation not found"}); events.publish(c.workspace_id,"conversation.read",{conversationId:c.id}); res.json({conversation:c}); } catch(error){ fail(res,error); } });
  router.patch("/conversations/:id/assignment", async (req,res) => { try { const existing=await repository.conversation(workspaceIds(req),req.params.id); if(!existing)return res.status(404).json({error:"Conversation not found"}); const userId=String(req.body.userId||"")||null; if(userId && !(await repository.member(existing.workspace_id,userId)))return res.status(400).json({error:"Assignee is not a workspace member"}); const c=await repository.assign(workspaceIds(req),req.params.id,userId); await store.addAudit(req.user.id,"inbox.conversation.assigned",{workspaceId:c.workspace_id,conversationId:c.id,userId}); events.publish(c.workspace_id,"conversation.assigned",{conversationId:c.id,userId}); res.json({conversation:c}); } catch(error){ fail(res,error); } });
  router.get("/conversations/:id/notes", async (req,res) => { try { const notes=await repository.notes(workspaceIds(req),req.params.id); if(!notes)return res.status(404).json({error:"Conversation not found"}); res.json({notes}); } catch(error){ fail(res,error); } });
  router.post("/conversations/:id/notes", async (req,res) => { const body=String(req.body.body||"").trim(); if(!body||body.length>4000)return res.status(400).json({error:"Note must contain 1 to 4000 characters"}); try { const note=await repository.addNote(workspaceIds(req),req.params.id,req.user.id,body); if(!note)return res.status(404).json({error:"Conversation not found"}); await store.addAudit(req.user.id,"inbox.note.created",{workspaceId:note.workspace_id,conversationId:req.params.id,noteId:note.id}); events.publish(note.workspace_id,"conversation.note",{conversationId:req.params.id}); res.status(201).json({note}); } catch(error){ fail(res,error); } });
  router.post("/conversations/:id/tags", async (req,res) => { const name=String(req.body.name||"").trim(); const color=String(req.body.color||"#25d366"); if(!name||name.length>50||!/^#[0-9a-fA-F]{6}$/.test(color))return res.status(400).json({error:"Valid tag name and hex color are required"}); try { const tag=await repository.addTag(workspaceIds(req),req.params.id,name,color); if(!tag)return res.status(404).json({error:"Conversation not found"}); events.publish(tag.workspace_id,"conversation.tag",{conversationId:req.params.id}); res.status(201).json({tag}); } catch(error){ fail(res,error); } });
  router.delete("/conversations/:id/tags/:tagId", async (req,res) => { try { const removed=await repository.removeTag(workspaceIds(req),req.params.id,req.params.tagId); if(removed===null)return res.status(404).json({error:"Conversation not found"}); res.json({removed}); } catch(error){ fail(res,error); } });
  router.post("/conversations/:id/manual-handoff", async (req,res) => { try { const c=await repository.conversation(workspaceIds(req),req.params.id); if(!c)return res.status(404).json({error:"Conversation not found"}); const config=remoteDesktopConfig(); if(!config.enabled||!config.url.includes("{workspaceId}")||!config.url.includes("{numberId}"))return res.status(503).json({error:"Workspace-scoped manual desktop is not configured yet"}); const url=config.url.replaceAll("{workspaceId}",encodeURIComponent(c.workspace_id)).replaceAll("{numberId}",encodeURIComponent(c.whatsapp_number_id)); await store.addAudit(req.user.id,"manual_handoff.opened",{workspaceId:c.workspace_id,conversationId:c.id,numberId:c.whatsapp_number_id}); res.json({handoff:{url,label:config.label,workspaceId:c.workspace_id,numberId:c.whatsapp_number_id}}); } catch(error){ fail(res,error); } });
  router.get("/events", (req,res) => { const ids=workspaceIds(req); res.set({"Content-Type":"text/event-stream","Cache-Control":"no-cache, no-transform","Connection":"keep-alive"}); res.flushHeaders(); const send=(event)=>res.write(`event: inbox\ndata: ${JSON.stringify(event)}\n\n`); res.write(": connected\n\n"); const unsubscribe=events.subscribe(ids,send); const heartbeat=setInterval(()=>res.write(": heartbeat\n\n"),25000); req.on("close",()=>{clearInterval(heartbeat);unsubscribe();}); });
  return router;
}

module.exports = { createInboxRouter };
