const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const crypto=require('node:crypto');
const flush=()=>new Promise(r=>setImmediate(r));
function harness(){
 const elements=new Map();const element=()=>({value:'',options:[],children:[],textContent:'',disabled:false,hidden:false,add(o){this.options.push(o);if(!this.value)this.value=o.value;},append(...e){this.children.push(...e);},replaceChildren(){this.children=[];this.options=[];},play:async()=>{}});
 const el=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id);};const view={querySelector:s=>el(s.slice(1))};let interval;const writes=[];let transportFailure=true,callRows=[];
 class Audio{constructor(){this.pc=null;this.stream=null;}async prepare(){this.pc={};this.stream={};}async localDescription(){return 'v=0 offer';}close(){this.pc=null;this.stream=null;}mute(){}async answer(){this.pc.currentRemoteDescription={};}}
 const fetch=async(url,options={})=>{let data;if(options.method==='POST'){writes.push({url,body:JSON.parse(options.body),key:options.headers['Idempotency-Key']});if(transportFailure)throw new TypeError('Network lost');data={state:'accepted',sessionId:'session',result:{callId:'wacid.test'}};}else if(url==='/api/session')data={csrfToken:'test'};else if(url==='/api/calling/connections')data={userId:'u',connections:[{id:'c',workspace_id:'w',workspace_name:'Test',phone:'+1234567890'}]};else if(url.includes('/permissions?'))data={canStartCall:true};else data={sessions:callRows};return {ok:true,status:200,json:async()=>data};};
 const context={document:{querySelector:()=>view,createElement:()=>element(),head:{append(){}}},window:{WaCallingAudio:{AudioSession:Audio},addEventListener(){}},navigator:{},Option:function(label,value){this.value=value;},crypto,fetch,AbortController,setTimeout,clearTimeout,setInterval:fn=>interval=fn,console};vm.runInNewContext(fs.readFileSync(require.resolve('../public/calling-setup'),'utf8'),context);
 return {el,writes,setFailure:v=>transportFailure=v,poll:()=>interval(),setRows:v=>callRows=v};
}
test('network loss retains command key; explicit check does not create a second call',async()=>{const h=harness();await flush();h.el('recipient').value='+923001234567';await h.el('start').onclick();assert.equal(h.writes.length,1);assert.equal(h.el('start').disabled,true);assert.equal(h.el('retry').hidden,false);h.setFailure(false);await h.el('retry').onclick();assert.equal(h.writes.length,2);assert.equal(h.writes[0].key,h.writes[1].key);assert.deepEqual(h.writes[0].body,h.writes[1].body);assert.equal(h.el('end').disabled,false);});
test('terminal webhook state releases microphone and permits another call',async()=>{const h=harness();await flush();h.setFailure(false);h.el('recipient').value='+923001234567';await h.el('start').onclick();h.setRows([{id:'session',external_call_id:'wacid.test',state:'terminated',direction:'outbound',owner_user_id:'u',created_at:new Date().toISOString()}]);h.poll();await flush();assert.equal(h.el('start').disabled,false);assert.equal(h.el('mute').disabled,true);assert.equal(h.el('end').disabled,true);});
