const test=require('node:test');const assert=require('node:assert/strict');
const {AudioSession}=require('../public/calling-audio');
function fixture(){const track={enabled:true,stopped:false,stop(){this.stopped=true;}};const stream={getTracks:()=>[track],getAudioTracks:()=>[track]};class PC{constructor(){this.iceGatheringState='complete';}addTrack(){}getTransceivers(){return [];}async createOffer(){return {type:'offer',sdp:'offer'};}async createAnswer(){return {type:'answer',sdp:'answer'};}async setLocalDescription(d){this.localDescription=d;}async setRemoteDescription(d){this.currentRemoteDescription=d;}close(){this.closed=true;}}const audio={srcObject:null,play:async()=>{}};return {track,stream,PC,audio,session:new AudioSession({mediaDevices:{getUserMedia:async()=>stream},PeerConnection:PC,audio})};}
test('outbound offer and answer, mute, and cleanup stop capture',async()=>{const f=fixture();await f.session.prepare();assert.equal(await f.session.localDescription(),'offer');await f.session.answer('remote');assert.equal(f.session.pc.currentRemoteDescription.sdp,'remote');f.session.mute(true);assert.equal(f.track.enabled,false);const pc=f.session.pc;f.session.close();assert.equal(pc.closed,true);assert.equal(f.track.stopped,true);assert.equal(f.audio.srcObject,null);});
test('inbound uses remote offer and local answer',async()=>{const f=fixture();await f.session.prepare();assert.equal(await f.session.localDescription('remote-offer'),'answer');assert.equal(f.session.pc.currentRemoteDescription.type,'offer');f.session.close();});
test('cancelled microphone prompt cannot leave capture running',async()=>{const f=fixture();let resolve;f.session.mediaDevices.getUserMedia=()=>new Promise(r=>resolve=r);const result=f.session.prepare();f.session.close();resolve(f.stream);await assert.rejects(result,/cancelled/);assert.equal(f.track.stopped,true);assert.equal(f.session.pc,null);});
test('denied microphone does not create peer connection',async()=>{const f=fixture();f.session.mediaDevices.getUserMedia=async()=>{throw Object.assign(new Error(),{name:'NotAllowedError'});};await assert.rejects(f.session.prepare(),/Microphone access was blocked/);assert.equal(f.session.pc,null);});
test('output routing uses the selected sink and surfaces unsupported or denied routes',async()=>{const f=fixture();await assert.rejects(f.session.output('headset'),/system audio route/);let sink;f.audio.setSinkId=async id=>{sink=id;};await f.session.output('headset');assert.equal(sink,'headset');await f.session.output('');assert.equal(sink,'');f.audio.setSinkId=async()=>{throw Object.assign(new Error('denied'),{name:'NotAllowedError'});};await assert.rejects(f.session.output('blocked'),{name:'NotAllowedError'});});
test('microphone selection is passed to capture without requesting video',async()=>{const f=fixture();let constraints;f.session.mediaDevices.getUserMedia=async c=>{constraints=c;return f.stream;};await f.session.prepare('headset-mic');assert.deepEqual(constraints.audio.deviceId,{exact:'headset-mic'});assert.equal(constraints.video,false);f.session.close();});
