const test = require("node:test");
const assert = require("node:assert/strict");
const { CanonicalSendService, SendError, normalizeIdempotencyKey, normalizeText } = require("../src/messaging/canonicalSendService");
const { OpenWaMessagingAdapter } = require("../src/messaging/openWaAdapter");
function fixture(overrides = {}) {
  const calls = [];
  const dispatch = { workspaceId: "workspace-a", conversationId: "conversation-a", numberId: "number-a", providerConnectionId: "connection-a", provider: "openwa", providerStatus: "active", automationEnabled: true, contactPhone: "+923001112222" };
  const repository = { async resolveConversationDispatch() { return dispatch; }, async reserveOutbound(input) { return { created: true, attempt: { id: "attempt-a", status: "reserved", request_hash: input.requestHash } }; }, async markDispatching(input) { calls.push(["dispatching", input]); }, async markProviderAccepted(input) { calls.push(["providerAccepted", input]); }, async failOutbound(input) { calls.push(["fail", input]); }, async recordOutbound(input) { calls.push(["record", input]); return { id: "message-a", status: "accepted" }; }, ...overrides.repository };
  const adapters = { openwa: { async sendText(input) { calls.push(["send", input]); return { externalMessageId: "provider-a", rawStatus: "queued" }; } }, ...overrides.adapters };
  const events = { publish(...args) { calls.push(["event", ...args]); } }; const audit = async (...args) => calls.push(["audit", ...args]);
  return { calls, service: new CanonicalSendService({ repository, adapters, events, audit }) };
}
test("canonical send records the exact provider with recoverable state transitions", async () => { const { service, calls } = fixture(); const result = await service.sendText({ actorId: "agent-a", workspaceIds: ["workspace-a"], conversationId: "conversation-a", text: " Hello ", idempotencyKey: "mobile-1" }); assert.equal(result.duplicate, false); assert.deepEqual(calls.map((call) => call[0]), ["dispatching", "send", "providerAccepted", "record", "event", "audit"]); });
test("canonical send returns an existing completed idempotent result without dispatch", async () => { const { service, calls } = fixture({ repository: { async reserveOutbound(input) { return { created: false, attempt: { id: "attempt-existing", status: "accepted", request_hash: input.requestHash, message_id: "existing", external_message_id: "provider-existing", message_status: "accepted" } }; } } }); const result = await service.sendText({ actorId: "agent-a", workspaceIds: ["workspace-a"], conversationId: "conversation-a", text: "Hello", idempotencyKey: "mobile-1" }); assert.equal(result.message.id, "existing"); assert.deepEqual(calls, []); });
test("canonical send rejects inactive provider connections before reservation", async () => { const { service, calls } = fixture({ repository: { async resolveConversationDispatch() { return { workspaceId: "workspace-a", conversationId: "conversation-a", numberId: "number-a", providerConnectionId: "connection-a", provider: "openwa", providerStatus: "disabled", automationEnabled: true, contactPhone: "+923001112222" }; } } }); await assert.rejects(service.sendText({ actorId: "agent-a", workspaceIds: ["workspace-a"], conversationId: "conversation-a", text: "Hello", idempotencyKey: "inactive-1" }), (error) => error.code === "PROVIDER_CONNECTION_INACTIVE"); assert.deepEqual(calls, []); });
test("canonical send rejects key reuse with a different payload", async () => { const { service, calls } = fixture({ repository: { async reserveOutbound() { return { created: false, attempt: { id: "attempt-existing", status: "accepted", request_hash: "different" } }; } } }); await assert.rejects(service.sendText({ actorId: "agent-a", workspaceIds: ["workspace-a"], conversationId: "conversation-a", text: "Hello", idempotencyKey: "reused-1" }), (error) => error.code === "IDEMPOTENCY_KEY_REUSED"); assert.deepEqual(calls, []); });
test("canonical send fails closed when a provider adapter is unavailable", async () => { const { service } = fixture({ adapters: { openwa: undefined } }); service.adapters.delete("openwa"); await assert.rejects(service.sendText({ actorId: "agent-a", workspaceIds: ["workspace-a"], conversationId: "conversation-a", text: "Hello", idempotencyKey: "mobile-1" }), (error) => error instanceof SendError && error.code === "PROVIDER_UNAVAILABLE"); });
test("canonical send marks a dispatching attempt failed when provider dispatch fails", async () => { const { service, calls } = fixture({ adapters: { openwa: { async sendText() { const error = new Error("network down"); error.code = "TEMPORARY_PROVIDER_FAILURE"; throw error; } } } }); await assert.rejects(service.sendText({ actorId: "agent-a", workspaceIds: ["workspace-a"], conversationId: "conversation-a", text: "Hello", idempotencyKey: "mobile-failure" }), (error) => error.code === "TEMPORARY_PROVIDER_FAILURE"); assert.deepEqual(calls.map((call) => call[0]), ["dispatching", "fail"]); });
test("canonical send validates message and idempotency input", () => { assert.equal(normalizeText(" hello "), "hello"); assert.equal(normalizeIdempotencyKey(" key "), "key"); assert.throws(() => normalizeText(""), /1 to 4096/); assert.throws(() => normalizeIdempotencyKey(""), /idempotency key/); });
test("OpenWA adapter converts E.164 recipients without exposing credentials", async () => { const sent = []; const adapter = new OpenWaMessagingAdapter({ async sendText(to, text) { sent.push({ to, text }); return "openwa-message"; } }); const result = await adapter.sendText({ connection: { provider: "openwa" }, to: "+92 300 111-2222", text: "Hello" }); assert.deepEqual(sent, [{ to: "923001112222@c.us", text: "Hello" }]); assert.equal(result.externalMessageId, "openwa-message"); });
