const test = require('node:test');
const assert = require('node:assert/strict');
const { mapGhlRole, normalizeIdentity } = require('../src/providers/ghlAutoProvisioning');
const { verifyAssertion } = require('../src/providers/ghlEmbeddedSso');

test('maps only allowlisted GHL role values to elevated internal roles', () => { assert.deepEqual(mapGhlRole('company_owner'), { internalRole: 'admin', mapped: true, source: 'company_owner' }); assert.deepEqual(mapGhlRole('unknown-provider-role'), { internalRole: 'agent', mapped: false, source: 'unknown-provider-role' }); });
test('requires server-side location identity', () => { assert.throws(() => normalizeIdentity({ token: { companyId: 'agency' } }), error => error.code === 'GHL_LOCATION_ID_UNVERIFIED'); });
test('normalizes verified provider identity without browser fields', () => { const value = normalizeIdentity({ token: { locationId: 'loc-1', companyId: 'agency-1', userId: 'user-1' }, profile: { email: 'User@Example.test', role: 'company_owner' } }); assert.equal(value.locationId, 'loc-1'); assert.equal(value.companyId, 'agency-1'); assert.equal(value.ghlUserId, 'user-1'); assert.equal(value.email, 'user@example.test'); assert.equal(value.roleType, 'company_owner'); });
test('verifies short-lived embedded assertions and rejects tampering', () => { const header=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'); const payload=Buffer.from(JSON.stringify({locationId:'loc-1',userId:'user-1',nonce:'n-1',iat:1000,exp:1300})).toString('base64url'); const body=`${header}.${payload}`; const crypto=require('node:crypto'); const token=`${body}.${crypto.createHmac('sha256','secret').update(body).digest('base64url')}`; assert.deepEqual(verifyAssertion(token,'secret',1100), { locationId:'loc-1', userId:'user-1', nonce:'n-1', iat:1000, exp:1300 }); assert.throws(() => verifyAssertion(`${body}.tampered`,'secret',1100), error => error.code === 'GHL_EMBEDDED_CONTEXT_INVALID'); });
