const test = require('node:test');
const assert = require('node:assert/strict');
const { mapGhlRole, normalizeIdentity, requiresMarketplaceInstallCorrelation } = require('../src/providers/ghlAutoProvisioning');
const { verifyAssertion } = require('../src/providers/ghlEmbeddedSso');
const { normalizeMarketplaceInstallEvent } = require('../src/providers/ghlMarketplaceInstall');

test('maps only allowlisted GHL role values to elevated internal roles', () => { assert.deepEqual(mapGhlRole('company_owner'), { internalRole: 'admin', mapped: true, source: 'company_owner' }); assert.deepEqual(mapGhlRole('unknown-provider-role'), { internalRole: 'agent', mapped: false, source: 'unknown-provider-role' }); });
test('requires server-side location identity', () => { assert.throws(() => normalizeIdentity({ token: { companyId: 'agency' } }), error => error.code === 'GHL_LOCATION_ID_UNVERIFIED'); });
test('uncorrelated first installs require one explicit private-test flag', () => { assert.equal(requiresMarketplaceInstallCorrelation({}), true); assert.equal(requiresMarketplaceInstallCorrelation({ GHL_ALLOW_UNCORRELATED_FIRST_INSTALL: 'false' }), true); assert.equal(requiresMarketplaceInstallCorrelation({ GHL_ALLOW_UNCORRELATED_FIRST_INSTALL: 'true' }), false); });
test('normalizes verified provider identity without browser fields', () => { const value = normalizeIdentity({ token: { locationId: 'loc-1', companyId: 'agency-1', userId: 'user-1' }, profile: { email: 'User@Example.test', role: 'company_owner' } }); assert.equal(value.locationId, 'loc-1'); assert.equal(value.companyId, 'agency-1'); assert.equal(value.ghlUserId, 'user-1'); assert.equal(value.email, 'user@example.test'); assert.equal(value.roleType, 'company_owner'); });
test('verifies short-lived embedded assertions and rejects tampering', () => { const header=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'); const payload=Buffer.from(JSON.stringify({locationId:'loc-1',userId:'user-1',nonce:'n-1',iat:1000,exp:1300})).toString('base64url'); const body=`${header}.${payload}`; const crypto=require('node:crypto'); const token=`${body}.${crypto.createHmac('sha256','secret').update(body).digest('base64url')}`; assert.deepEqual(verifyAssertion(token,'secret',1100000), { locationId:'loc-1', userId:'user-1', nonce:'n-1', iat:1000, exp:1300 }); assert.throws(() => verifyAssertion(`${body}.tampered`,'secret',1100000), error => error.code === 'GHL_EMBEDDED_CONTEXT_INVALID'); });
test('normalizes the official HighLevel App Install event identity', () => { const event = normalizeMarketplaceInstallEvent({ type:'INSTALL', appId:'app-1', versionId:'v1', installType:'Location', companyId:'company-1', locationId:'location-1', userId:'ghl-user-1', timestamp:'2025-06-25T06:57:06.225Z', webhookId:'webhook-1' }); assert.deepEqual(event, { type:'INSTALL', appId:'app-1', versionId:'v1', installType:'Location', companyId:'company-1', locationId:'location-1', userId:'ghl-user-1', webhookId:'webhook-1', eventTimestamp:new Date('2025-06-25T06:57:06.225Z') }); assert.throws(() => normalizeMarketplaceInstallEvent({ type:'INSTALL', appId:'app-1', companyId:'company-1', locationId:'location-1', webhookId:'webhook-2' }), error => error.code === 'GHL_MARKETPLACE_INSTALL_INVALID'); });
