const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {Pool}=require('pg');
const {runMigrations}=require('../src/db/migrate');
const {CredentialVault}=require('../src/security/credentialVault');
const {MetaWebhookRepository}=require('../src/messaging/metaWebhookRepository');
const {MetaCallService}=require('../src/messaging/metaCallService');
const {createMetaCallingRouter}=require('../src/messaging/metaCallingRoutes');
const url=process.env.TEST_DATABASE_URL;
test('calling durable lifecycle, authorization, encrypted signaling, deduplication and uncertain delivery',{skip:!url,timeout:120000},async()=>{
 const schema='calls_'+crypto.randomBytes(8).toString('hex');
 const admin=new Pool({connectionString:url}),pool=new Pool({connectionString:url,options:'-c search_path='+schema});
 const env={CONNECTOR_MASTER_KEY:crypto.randomBytes(32).toString('base64'),META_GRAPH_VERSION:'v26.0'};
 const vault=new CredentialVault({env});const connection=crypto.randomUUID();let server;
 try{
  await admin.query('CREATE SCHEMA '+schema);await runMigrations(pool);
  await pool.query(`INSERT INTO users(id,name,email,password_hash,role) VALUES('owner','Owner','owner@example.invalid','test','client'),('other','Other','other@example.invalid','test','client');
    INSERT INTO plans(id,name,workspace_limit,number_limit,user_limit) VALUES('plan','Test',5,5,5);
    INSERT INTO workspaces(id,owner_id,name,plan_id) VALUES('w','owner','Test','plan'),('w2','other','Other','plan');
    INSERT INTO workspace_members(id,workspace_id,user_id,role) VALUES('m','w','owner','owner');`);
  const sealed=vault.encrypt({accessToken:'test-only-token'},connection);
  await pool.query("INSERT INTO provider_connections(id,workspace_id,provider,label,status,encrypted_credentials,encryption_key_id) VALUES($1,'w','whatsapp_cloud','Test','active',$2,$3)",[connection,sealed.ciphertext,sealed.keyId]);
  await pool.query("INSERT INTO whatsapp_numbers(id,owner_id,workspace_id,label,phone,provider_connection_id) VALUES('n','owner','w','Test','+15551234567',$1)",[connection]);
  await pool.query("INSERT INTO meta_connection_assets(provider_connection_id,workspace_id,waba_id,phone_number_id) VALUES($1,'w','987','123')",[connection]);
  const repo=new MetaWebhookRepository(pool,{vault});let sent=0,permit=true,timeout=false;
  const target={workspaceId:'w',connectionId:connection,phoneNumberId:'123',numberId:'n',user:{id:'owner'},accessToken:'test-only-token'};
  const service=new MetaCallService({pool,vault,graph:{request:async args=>args.method==='POST'?{messages:[{id:'wamid.permission'}]}:{permission:{status:permit?'permanent':'no_permission'},actions:[{action_name:'start_call',can_perform_action:permit},{action_name:'send_call_permission_request',can_perform_action:true}]}},calling:{action:async input=>{sent++;if(timeout)throw Object.assign(new Error(),{code:'META_TIMEOUT'});return input.action==='connect'?{calls:[{id:'wacid.out'}]}:{success:true};}}});
  const wrap=(calls,statuses)=>({object:'whatsapp_business_account',entry:[{id:'987',changes:[{field:'calls',value:{metadata:{phone_number_id:'123'},calls,statuses}}]}]});
  const now=Math.floor(Date.now()/1000);
  const offer={id:'wacid.in',event:'connect',timestamp:now,direction:'USER_INITIATED',from:'923001234567',session:{sdp_type:'offer',sdp:'v=0\r\na=ice-pwd:secret-test'}};
  assert.equal((await repo.admit(wrap([offer]))).accepted,1);
  assert.equal((await repo.admit(wrap([offer]))).duplicates,1);
  assert.ok(!(await pool.query('SELECT payload FROM webhook_receipts')).rows.map(r=>JSON.stringify(r)).join('').includes('secret-test'));
  const drain=async()=>{for(const receipt of await repo.claim())await repo.processReceipt(receipt);};await drain();
  let incoming=(await service.list(target))[0];assert.equal(incoming.state,'ringing');
  await assert.rejects(()=>service.signaling(target,incoming.id),e=>e.code==='META_CALL_NOT_FOUND');
  await service.claim(target,incoming.id);
  await assert.rejects(()=>service.claim({...target,user:{id:'other'}},incoming.id),e=>e.code==='META_CALL_CLAIM_UNAVAILABLE');
  await assert.rejects(()=>service.signaling({...target,workspaceId:'w2'},incoming.id),e=>e.code==='META_CALL_NOT_FOUND');
  assert.equal((await service.signaling(target,incoming.id)).session.sdp,offer.session.sdp);
  const answer='v=0\r\na=ice-pwd:answer-test';
  let response=await service.action(target,{action:'pre_accept',callId:'wacid.in',sdp:answer},'preaccept-12345678');assert.equal(response.state,'accepted');
  await assert.rejects(()=>service.action(target,{action:'accept',callId:'wacid.in',sdp:'v=0 different'},'accept-different-12'),e=>e.code==='META_CALL_SDP_MISMATCH');
  await service.action(target,{action:'accept',callId:'wacid.in',sdp:answer},'accept-1234567890');
  await repo.admit(wrap([{...offer,event:'terminate',timestamp:now+3,session:undefined}]));await drain();
  await repo.admit(wrap([{...offer,timestamp:now+1}]));await drain();
  incoming=(await service.list(target)).find(s=>s.id===incoming.id);assert.equal(incoming.state,'terminated');
  assert.equal((await pool.query('SELECT remote_session FROM meta_call_sessions WHERE id=$1',[incoming.id])).rows[0].remote_session,null);
  const input={action:'connect',to:'923001234567',sdp:answer};permit=false;
  await assert.rejects(()=>service.action(target,input,'outbound-12345678'),e=>e.code==='META_CALL_PERMISSION_REQUIRED');permit=true;
  response=await service.action(target,input,'outbound-12345678');const before=sent;
  assert.equal((await service.action(target,input,'outbound-12345678')).commandId,response.commandId);assert.equal(sent,before);
  await assert.rejects(()=>service.action(target,{...input,to:'923001234568'},'outbound-12345678'),e=>e.code==='IDEMPOTENCY_CONFLICT');
  await assert.rejects(()=>service.action(target,input,'outbound-new-1234'),e=>e.code==='META_CALL_ALREADY_ACTIVE');
  timeout=true;const uncertainInput={...input,to:'923001234569'};
  response=await service.action(target,uncertainInput,'uncertain-12345678');assert.equal(response.state,'uncertain');const count=sent;
  await service.action(target,uncertainInput,'uncertain-12345678');assert.equal(sent,count);
  await assert.rejects(()=>service.action(target,{action:'request_permission',to:'923001234567',text:'May we call you?'},'permission-12345678'),e=>e.code==='META_CALL_TEMPLATE_REQUIRED');
  await pool.query("INSERT INTO suppressions(id,workspace_id,phone_e164,scope,reason) VALUES('s','w','+923001234560','workspace','opted out')");
  await assert.rejects(()=>service.action(target,{...input,to:'923001234560'},'suppressed-12345678'),e=>e.code==='META_CALL_RECIPIENT_SUPPRESSED');
  assert.equal((await pool.query('SELECT count(*)::int n FROM messages')).rows[0].n,0);
  assert.equal((await pool.query('SELECT count(*)::int n FROM outbox_events')).rows[0].n,0);
  const inbound={object:'whatsapp_business_account',entry:[{id:'987',changes:[{field:'messages',value:{metadata:{phone_number_id:'123'},messages:[{id:'wamid.customer',from:'923001234567',type:'text',text:{body:'Please help with my order'},timestamp:String(now)}]}}]}]};
  await repo.admit(inbound);await drain();
  const permissionResponse=await service.action(target,{action:'request_permission',to:'923001234567',text:'May we call to help with your order?'},'permission-12345678');
  assert.equal(permissionResponse.state,'accepted');
  assert.equal((await pool.query("SELECT body FROM messages WHERE external_message_id='wamid.permission'")).rows[0].body,'May we call to help with your order?');
  const detail=await service.detail(target,incoming.id);assert.ok(detail.events.some(e=>e.event==='terminate'));assert.equal(detail.session.state,'terminated');
  await assert.rejects(()=>service.detail({...target,workspaceId:'w2'},incoming.id),e=>e.code==='META_CALL_NOT_FOUND');
  const stale={...offer,id:'wacid.stale',timestamp:now-300};await repo.admit(wrap([stale]));await drain();
  assert.equal((await pool.query("SELECT remote_session FROM meta_call_sessions WHERE external_call_id='wacid.stale'")).rows[0].remote_session,null);
  const pendingId=crypto.randomUUID();
  await pool.query("INSERT INTO meta_call_commands(id,workspace_id,provider_connection_id,actor_id,idempotency_key,request_hash,action,state,created_at) VALUES($1,'w',$2,'owner','crashed-request-123','hash','connect','sending',now()-interval '2 minutes')",[pendingId,connection]);
  await service.sweep();assert.equal((await pool.query('SELECT state FROM meta_call_commands WHERE id=$1',[pendingId])).rows[0].state,'uncertain');
  const persisted=JSON.stringify((await pool.query('SELECT * FROM meta_call_commands')).rows);assert.ok(!persisted.includes('answer-test'));assert.ok(!persisted.includes('test-only-token'));
  const {callingConnections}=require('../src/messaging/metaCallingAccess');
  const {listContacts,createContactDirectoryRouter}=require('../src/messaging/contactDirectory');
  const contactConnection={id:connection,workspace_id:'w',number_id:'n'};
  const contactList=await listContacts(pool,contactConnection);
  assert.ok(contactList.contacts.some(c=>c.phone_e164==='+923001234567'&&c.has_calls));
  await pool.query("INSERT INTO contacts(id,workspace_id,phone_e164,display_name) VALUES('isolated','w2','+923009999999','Other tenant'),('unrelated','w','+923008888888','Other number')");
  assert.equal((await listContacts(pool,contactConnection,{search:'Other'})).contacts.length,0);
  await assert.rejects(listContacts(pool,contactConnection,{offset:-1}),/Invalid offset/);
  await pool.query("UPDATE contacts SET display_name='Saved name' WHERE workspace_id='w' AND phone_e164='+923001234567'");
  assert.equal((await callingConnections(pool,'owner')).length,1);
  assert.equal((await callingConnections(pool,'other')).length,0);
  await pool.query("INSERT INTO workspace_members(id,workspace_id,user_id,role) VALUES('agent-member','w','other','agent')");
  assert.equal((await callingConnections(pool,'other')).length,0);
  await pool.query("INSERT INTO whatsapp_number_assignments(id,workspace_id,whatsapp_number_id,user_id) VALUES('assignment','w','n','other')");
  assert.equal((await callingConnections(pool,'other')).length,1);
  assert.equal((await callingConnections(pool,'owner',{ghlEmbedded:true,ghlWorkspaceId:'w2',ghlLocationId:'wrong'})).length,0);
  await pool.query("INSERT INTO ghl_installations(id,installation_id,location_id,workspace_id,encrypted_credentials,encryption_key_id,access_token_expires_at) VALUES('ghl','ghl-install','location','w',$1,'test',now()+interval '1 hour')",[Buffer.from('test')]);
  const embedded={ghlEmbedded:true,ghlWorkspaceId:'w',ghlLocationId:'location'};
  assert.equal((await callingConnections(pool,'other',embedded)).length,1);
  assert.equal((await callingConnections(pool,'other',{...embedded,ghlLocationId:'wrong'})).length,0);
  await pool.query("UPDATE ghl_installations SET status='revoked' WHERE id='ghl'");
  assert.equal((await callingConnections(pool,'other',embedded)).length,0);
  await pool.query("UPDATE whatsapp_number_assignments SET removed_at=now() WHERE id='assignment'");
  assert.equal((await callingConnections(pool,'other')).length,0);
  const {recordPermissionReply,permissionHistory}=require('../src/messaging/metaCallPermissions');
  const permissionPayload={direction:'inbound',value:{message:{id:'wamid.grant',from:'923001234567',timestamp:String(now+10),interactive:{type:'call_permission_reply',call_permission_reply:{response:'accept',is_permanent:false,expiration_timestamp:String(now+86400),response_source:'user_action'}}}}};
  const permissionAsset={workspace_id:'w',provider_connection_id:connection};
  await recordPermissionReply(pool,permissionAsset,permissionPayload);await recordPermissionReply(pool,permissionAsset,permissionPayload);
  let records=await permissionHistory(pool,target);assert.equal(records.filter(p=>p.external_event_id==='reply:wamid.grant').length,1);assert.equal(records[0].status,'temporary');assert.equal(records[0].expires_at.toISOString(),new Date((now+86400)*1000).toISOString());
  await recordPermissionReply(pool,permissionAsset,{...permissionPayload,history:true,value:{message:{...permissionPayload.value.message,id:'wamid.import'}}});
  assert.equal((await pool.query("SELECT count(*)::int n FROM meta_call_permissions WHERE external_event_id='reply:wamid.import'")).rows[0].n,0);
  assert.equal((await permissionHistory(pool,{...target,workspaceId:'w2'})).length,0);
  await pool.query("UPDATE meta_call_commands SET created_at=now()-interval '1 minute' WHERE action='request_permission'");
  let sentTemplate;
  const templateService=new MetaCallService({pool,vault,calling:{},graph:{request:async args=>{
    if(args.method==='POST'){sentTemplate=args.body;return {messages:[{id:'wamid.permission-template'}]};}
    if(args.path[1]==='message_templates')return {data:[{name:'call_help',language:'en_US',status:'APPROVED',category:'UTILITY',components:[{type:'BODY',text:'May we call about your order?'},{type:'CALL_PERMISSION_REQUEST'}]}]};
    return {permission:{status:'no_permission'},actions:[{action_name:'send_call_permission_request',can_perform_action:true}]};
  }}});
  const templateInput={action:'request_permission',to:'923001234588',text:'May we call?',template:{name:'call_help',language:'en_US'}};
  assert.equal((await templateService.action(target,templateInput,'template-request-1234')).state,'accepted');assert.equal(sentTemplate.type,'template');assert.equal(sentTemplate.template.name,'call_help');assert.equal(sentTemplate.interactive,undefined);
  const saved=await templateService.action(target,templateInput,'template-request-1234');assert.equal(saved.result.mode,'template');
  const express=require('express');const app=express();const csrf='a'.repeat(64);
  app.use((req,_res,next)=>{req.session={userId:req.get('x-test-user')||'owner',csrfToken:csrf};next();});
  app.use('/api/:connectionId/calling',createMetaCallingRouter({enabled:true,env,origin:'https://example.invalid',store:{driver:'postgres',repository:{pool},findUser:id=>({id,active:true,role:'client'})},fetchImpl:async()=>{throw new Error('No live calls in tests');}}));
  app.use('/directory',require('../src/messaging/metaCallingAccess').createCallingDirectoryRouter({pool,enabled:true}));
  app.use('/contacts',createContactDirectoryRouter({pool}));
  await repo.admit(wrap([{...offer,id:'wacid.popup',timestamp:Math.floor(Date.now()/1000)}]));await drain();
  server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/'+connection+'/calling';
  const directoryUrl='http://127.0.0.1:'+server.address().port+'/directory/incoming';
  const contactUrl='http://127.0.0.1:'+server.address().port+'/contacts/?connectionId='+connection;
  const contactResponse=await fetch(contactUrl);
  assert.equal(contactResponse.status,200);assert.equal(contactResponse.headers.get('cache-control'),'no-store');
  assert.ok((await contactResponse.json()).contacts.some(c=>c.display_name==='Saved name'));
  assert.equal((await fetch(contactUrl,{headers:{'x-test-user':'other'}})).status,404);
  assert.equal((await (await fetch(directoryUrl)).json()).sessions.length,1);
  assert.equal((await (await fetch(directoryUrl,{headers:{'x-test-user':'other'}})).json()).sessions.length,0);
  assert.equal((await fetch(base+'/sessions?workspaceId=w')).status,200);
  assert.equal((await fetch(base+'/sessions?workspaceId=w',{headers:{'x-test-user':'other'}})).status,404);
  assert.equal((await fetch(base+'/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId:'w'})})).status,403);
 }finally{if(server)await new Promise(r=>server.close(r));await pool.end();await admin.query('DROP SCHEMA IF EXISTS '+schema+' CASCADE');await admin.end();}
});
