process.env.MOCK_BROWSER = "1";
process.env.NODE_ENV = "test";
process.env.SESSION_SECRET = "test-secret-that-is-long-enough-for-local-tests";
const test = require("node:test");
const assert = require("node:assert/strict");
const bcrypt = require("bcryptjs");
const { app, store } = require(require("node:path").resolve("src/server"));
let server, originalData, admin, one, two, first, second;
function cookieFrom(response) { const value = response.headers.get("set-cookie"); return value ? value.split(";")[0] : ""; }
async function request(base, path, options = {}) { const response = await fetch(base + path, options); const body = await response.json().catch(() => ({})); return { response, body }; }
async function login(base, email, password) { const session = await request(base, "/api/session"); const cookie = cookieFrom(session.response); const result = await request(base, "/api/login", { method: "POST", headers: { "content-type": "application/json", cookie, "x-csrf-token": session.body.csrfToken }, body: JSON.stringify({ email, password }) }); assert.equal(result.response.status, 200); return { cookie: cookieFrom(result.response) || cookie, csrf: result.body.csrfToken }; }
async function api(base, auth, path, options = {}) { return request(base, path, { ...options, headers: { "content-type": "application/json", cookie: auth.cookie, "x-csrf-token": auth.csrf, ...(options.headers || {}) } }); }
test.before(async () => { originalData = store.data; admin = { id: "admin-owner-test", name: "Administrator", email: "owner-admin@test.local", passwordHash: await bcrypt.hash("AdminPassword123!", 4), role: "admin", active: true, createdAt: new Date().toISOString() }; one = { id: "client-owner-one", name: "Client One", email: "owner-one@test.local", passwordHash: await bcrypt.hash("ClientPassword123!", 4), role: "client", active: true, createdAt: new Date().toISOString() }; two = { id: "client-owner-two", name: "Client Two", email: "owner-two@test.local", passwordHash: await bcrypt.hash("ClientPassword123!", 4), role: "client", active: true, createdAt: new Date().toISOString() }; first = { id: "account-owner-one", ownerId: one.id, label: "One workspace", phone: "+923001111111", createdAt: new Date().toISOString(), lastLaunchedAt: null }; second = { id: "account-owner-two", ownerId: two.id, label: "Two workspace", phone: "+923002222222", createdAt: new Date().toISOString(), lastLaunchedAt: null }; store.data = { users: [admin, one, two], accounts: [first, second], audit: [] }; server = await new Promise(resolve => { const instance = app.listen(0, "127.0.0.1", () => resolve(instance)); }); });
test.after(async () => { store.data = originalData; await new Promise(resolve => server.close(resolve)); });
test("client can only list its own workspaces", async () => { const base = "http://127.0.0.1:" + server.address().port; const auth = await login(base, one.email, "ClientPassword123!"); const result = await api(base, auth, "/api/accounts"); assert.equal(result.response.status, 200); assert.deepEqual(result.body.accounts.map(account => account.id), [first.id]); });
test("client cannot launch or delete another client workspace", async () => { const base = "http://127.0.0.1:" + server.address().port; const auth = await login(base, one.email, "ClientPassword123!"); const launch = await api(base, auth, "/api/accounts/" + second.id + "/launch", { method: "POST" }); const remove = await api(base, auth, "/api/accounts/" + second.id, { method: "DELETE" }); assert.equal(launch.response.status, 404); assert.equal(remove.response.status, 404); assert.ok(store.findAccount(second.id)); });
test("admin can see and remove any client workspace", async () => { const base = "http://127.0.0.1:" + server.address().port; const auth = await login(base, admin.email, "AdminPassword123!"); const list = await api(base, auth, "/api/accounts"); assert.equal(list.response.status, 200); assert.deepEqual(list.body.accounts.map(account => account.id).sort(), [first.id, second.id].sort()); const remove = await api(base, auth, "/api/accounts/" + second.id, { method: "DELETE" }); assert.equal(remove.response.status, 200); assert.equal(store.findAccount(second.id), undefined); });
