const crypto = require('node:crypto');
const bcrypt = require('bcryptjs');
const express = require('express');

function base64url(value) { return Buffer.from(value).toString('base64url'); }
function verifyAssertion(token, secret, now = Date.now()) {
  const parts = String(token || '').split('.');
  if (parts.length !== 3 || !secret) throw Object.assign(new Error('Signed HighLevel context is required'), { code: 'GHL_EMBEDDED_CONTEXT_REQUIRED', status: 401 });
  let header; let payload;
  try { header = JSON.parse(Buffer.from(parts[0], 'base64url').toString()); payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString()); } catch { throw Object.assign(new Error('Signed HighLevel context is invalid'), { code: 'GHL_EMBEDDED_CONTEXT_INVALID', status: 401 }); }
  if (header.alg !== 'HS256') throw Object.assign(new Error('Unsupported HighLevel context signature'), { code: 'GHL_EMBEDDED_CONTEXT_INVALID', status: 401 });
  const expected = crypto.createHmac('sha256', secret).update(`${parts[0]}.${parts[1]}`).digest('base64url');
  if (expected.length !== parts[2].length || !crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(parts[2]))) throw Object.assign(new Error('HighLevel context signature is invalid'), { code: 'GHL_EMBEDDED_CONTEXT_INVALID', status: 401 });
  const seconds = Math.floor(now / 1000);
  if (!payload.nonce || !Number.isSafeInteger(payload.exp) || !Number.isSafeInteger(payload.iat) || payload.exp <= seconds || payload.exp - seconds > 600 || payload.iat > seconds + 30) throw Object.assign(new Error('HighLevel context is expired or outside the allowed clock window'), { code: 'GHL_EMBEDDED_CONTEXT_EXPIRED', status: 401 });
  if (!payload.locationId || !payload.userId) throw Object.assign(new Error('HighLevel context is missing location or user identity'), { code: 'GHL_EMBEDDED_CONTEXT_INVALID', status: 401 });
  return payload;
}
function authUser(req, store) { const user = req.session?.userId && store.findUser(req.session.userId); return user?.active ? user : null; }
function createGhlEmbeddedRouter({ pool, store, env = process.env } = {}) {
  if (typeof pool?.connect !== 'function') throw new TypeError('Embedded SSO requires PostgreSQL');
  const router = express.Router();
  router.post('/session', express.json({ limit: '8kb', strict: true }), async (req, res) => {
    const client = await pool.connect();
    try {
      const payload = verifyAssertion(req.body?.assertion, env.GHL_EMBEDDED_SIGNING_SECRET);
      await client.query('BEGIN');
      const claimed = await client.query('INSERT INTO ghl_embedded_bootstrap_states(id,nonce_hash,expires_at) VALUES($1,$2,to_timestamp($3)) ON CONFLICT(nonce_hash) DO NOTHING RETURNING id', [crypto.randomUUID(), crypto.createHash('sha256').update(String(payload.nonce)).digest('hex'), payload.exp]);
      if (!claimed.rowCount) { await client.query('ROLLBACK'); return res.status(409).json({ error: 'Embedded context has already been used', code: 'GHL_EMBEDDED_REPLAY' }); }
      const result = await client.query(`SELECT i.workspace_id,i.location_id,i.installation_id,x.user_id,wm.role
        FROM ghl_installations i JOIN ghl_external_users x ON x.location_id=i.location_id AND x.ghl_user_id=$2
        JOIN workspace_members wm ON wm.workspace_id=i.workspace_id AND wm.user_id=x.user_id
        WHERE i.location_id=$1 AND i.status='active'`, [String(payload.locationId), String(payload.userId)]);
      const row = result.rows[0];
      if (!row || (payload.installationId && payload.installationId !== row.installation_id)) { await client.query('ROLLBACK'); return res.status(403).json({ error: 'HighLevel context is not authorized for this location', code: 'GHL_EMBEDDED_TENANT_DENIED' }); }
      await client.query('UPDATE ghl_embedded_bootstrap_states SET used_at=now() WHERE nonce_hash=$1', [crypto.createHash('sha256').update(String(payload.nonce)).digest('hex')]);
      await client.query('COMMIT');
      req.session.regenerate(error => { if (error) return res.status(503).json({ error: 'Could not start embedded session' }); req.session.userId = row.user_id; req.session.ghlEmbedded = true; req.session.ghlLocationId = row.location_id; req.session.ghlWorkspaceId = row.workspace_id; req.session.csrfToken = crypto.randomBytes(24).toString('hex'); req.session.cookie.maxAge = 30 * 60 * 1000; req.session.save(saveError => saveError ? res.status(503).json({ error: 'Could not save embedded session' }) : res.json({ authenticated: true, csrfToken: req.session.csrfToken, redirect: '/' })); });
    } catch (error) { try { await client.query('ROLLBACK'); } catch {} res.status(error.status || 503).json({ error: error.message, code: error.code || 'GHL_EMBEDDED_SESSION_FAILED' }); } finally { client.release(); }
  });
  router.get('/session', (req, res) => { const user = authUser(req, store); if (!user || !req.session.ghlEmbedded) return res.status(401).json({ authenticated: false }); res.json({ authenticated: true, user: store.publicUser(user), workspaceId: req.session.ghlWorkspaceId, locationId: req.session.ghlLocationId }); });
  return router;
}
function createActivationRouter({ pool, store } = {}) {
  const router = express.Router();
  async function manager(req, res, next) { const user = authUser(req, store); const workspaceId = String(req.body?.workspaceId || req.query?.workspaceId || ''); if (!user) return res.status(401).json({ error: 'Please sign in' }); const allowed = await pool.query("SELECT 1 FROM workspace_members WHERE workspace_id=$1 AND user_id=$2 AND role IN ('owner','admin')", [workspaceId, user.id]); if (user.role !== 'admin' && !allowed.rowCount) return res.status(404).json({ error: 'Workspace not found' }); req.workspaceId = workspaceId; req.actor = user; next(); }
  router.post('/invite', express.json({ limit: '8kb', strict: true }), manager, async (req, res) => { const userId = String(req.body.userId || ''); const member = await pool.query('SELECT 1 FROM workspace_members WHERE workspace_id=$1 AND user_id=$2', [req.workspaceId, userId]); if (!member.rowCount) return res.status(404).json({ error: 'Workspace user not found' }); const raw = crypto.randomBytes(32).toString('base64url'); await pool.query('UPDATE password_activation_tokens SET used_at=now() WHERE user_id=$1 AND used_at IS NULL', [userId]); await pool.query('INSERT INTO password_activation_tokens(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval \'30 minutes\')', [crypto.randomUUID(), userId, crypto.createHash('sha256').update(raw).digest('hex')]); res.status(201).json({ activationPath: `/activate.html?token=${encodeURIComponent(raw)}` }); });
  router.post('/complete', express.json({ limit: '8kb', strict: true }), async (req, res) => { const raw = String(req.body.token || ''); const password = String(req.body.password || ''); if (!raw || password.length < 10) return res.status(400).json({ error: 'Activation token and a password of at least 10 characters are required' }); const client = await pool.connect(); try { await client.query('BEGIN'); const result = await client.query('SELECT * FROM password_activation_tokens WHERE token_hash=$1 FOR UPDATE', [crypto.createHash('sha256').update(raw).digest('hex')]); const token = result.rows[0]; if (!token || token.used_at || new Date(token.expires_at) <= new Date()) { await client.query('ROLLBACK'); return res.status(400).json({ error: 'Activation token is invalid or expired' }); } const hash = await bcrypt.hash(password, 12); await client.query('UPDATE users SET password_hash=$1,password_activation_required=false WHERE id=$2', [hash, token.user_id]); await client.query('UPDATE password_activation_tokens SET used_at=now() WHERE id=$1', [token.id]); await client.query('COMMIT'); res.json({ activated: true }); } catch (error) { await client.query('ROLLBACK'); res.status(503).json({ error: 'Activation is temporarily unavailable' }); } finally { client.release(); } });
  return router;
}
function createAssignmentRouter({ pool, store } = {}) {
  const router = express.Router();
  async function context(req, res, managerOnly = false) { const user = authUser(req, store); const workspaceId = String(req.params.workspaceId || ''); if (!user) { res.status(401).json({ error: 'Please sign in' }); return null; } const membership = await pool.query('SELECT role FROM workspace_members WHERE workspace_id=$1 AND user_id=$2', [workspaceId, user.id]); const role = membership.rows[0]?.role; if (!role && user.role !== 'admin') { res.status(404).json({ error: 'Workspace not found' }); return null; } if (managerOnly && user.role !== 'admin' && !['owner','admin'].includes(role)) { res.status(403).json({ error: 'Workspace administrator access required' }); return null; } return { user, workspaceId }; }
  router.get('/:workspaceId/number-assignments', async (req, res) => { const ctx = await context(req, res); if (!ctx) return; const [assignments, unassigned] = await Promise.all([pool.query(`SELECT a.id,a.whatsapp_number_id,a.user_id,a.assigned_at,n.label,n.phone,u.name,u.email FROM whatsapp_number_assignments a JOIN whatsapp_numbers n ON n.id=a.whatsapp_number_id JOIN users u ON u.id=a.user_id WHERE a.workspace_id=$1 AND a.removed_at IS NULL ORDER BY n.label,u.name`, [ctx.workspaceId]), pool.query(`SELECT m.user_id,u.name,u.email FROM workspace_members m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=$1 AND NOT EXISTS (SELECT 1 FROM whatsapp_number_assignments a WHERE a.workspace_id=m.workspace_id AND a.user_id=m.user_id AND a.removed_at IS NULL) ORDER BY u.name`, [ctx.workspaceId])]); res.json({ assignments: assignments.rows, unassignedUsers: unassigned.rows }); });
  router.post('/:workspaceId/number-assignments', express.json({ limit: '8kb', strict: true }), async (req, res) => { const ctx = await context(req, res, true); if (!ctx) return; const numberId = String(req.body.whatsappNumberId || ''); const userId = String(req.body.userId || ''); const client = await pool.connect(); try { await client.query('BEGIN'); const number = await client.query('SELECT id FROM whatsapp_numbers WHERE id=$1 AND workspace_id=$2 FOR SHARE', [numberId, ctx.workspaceId]); const member = await client.query('SELECT 1 FROM workspace_members WHERE workspace_id=$1 AND user_id=$2 FOR SHARE', [ctx.workspaceId, userId]); if (!number.rowCount || !member.rowCount) throw Object.assign(new Error('Exact workspace number and member are required'), { status: 409 }); const current = await client.query('SELECT whatsapp_number_id FROM whatsapp_number_assignments WHERE workspace_id=$1 AND user_id=$2 AND removed_at IS NULL FOR UPDATE', [ctx.workspaceId, userId]); if (current.rowCount) { if (current.rows[0].whatsapp_number_id === numberId) { await client.query('COMMIT'); return res.json({ assigned: true, unchanged: true }); } throw Object.assign(new Error('User is already assigned to another number; use move'), { status: 409 }); } await client.query('INSERT INTO whatsapp_number_assignments(id,workspace_id,whatsapp_number_id,user_id) VALUES($1,$2,$3,$4)', [crypto.randomUUID(), ctx.workspaceId, numberId, userId]); await client.query('COMMIT'); res.status(201).json({ assigned: true }); } catch (error) { await client.query('ROLLBACK'); res.status(error.status || 503).json({ error: error.message || 'Assignment failed' }); } finally { client.release(); } });
  router.post('/:workspaceId/number-assignments/move', express.json({ limit: '8kb', strict: true }), async (req, res) => { const ctx = await context(req, res, true); if (!ctx) return; const toNumberId = String(req.body.whatsappNumberId || ''); const userId = String(req.body.userId || ''); const client = await pool.connect(); try { await client.query('BEGIN'); const valid = await client.query(`SELECT 1 FROM whatsapp_numbers n JOIN workspace_members m ON m.workspace_id=n.workspace_id WHERE n.id=$1 AND n.workspace_id=$2 AND m.user_id=$3 FOR SHARE`, [toNumberId, ctx.workspaceId, userId]); if (!valid.rowCount) throw Object.assign(new Error('Exact workspace number and member are required'), { status: 409 }); await client.query('SELECT id FROM whatsapp_number_assignments WHERE workspace_id=$1 AND user_id=$2 AND removed_at IS NULL FOR UPDATE', [ctx.workspaceId, userId]); await client.query('UPDATE whatsapp_number_assignments SET removed_at=now() WHERE workspace_id=$1 AND user_id=$2 AND removed_at IS NULL', [ctx.workspaceId, userId]); await client.query('INSERT INTO whatsapp_number_assignments(id,workspace_id,whatsapp_number_id,user_id) VALUES($1,$2,$3,$4)', [crypto.randomUUID(), ctx.workspaceId, toNumberId, userId]); await client.query('COMMIT'); res.json({ moved: true }); } catch (error) { await client.query('ROLLBACK'); res.status(error.status || 503).json({ error: error.message || 'Move failed' }); } finally { client.release(); } });
  router.delete('/:workspaceId/number-assignments/:numberId/users/:userId', async (req, res) => { const ctx = await context(req, res, true); if (!ctx) return; const result = await pool.query('UPDATE whatsapp_number_assignments SET removed_at=now() WHERE workspace_id=$1 AND whatsapp_number_id=$2 AND user_id=$3 AND removed_at IS NULL RETURNING id', [ctx.workspaceId, req.params.numberId, req.params.userId]); if (!result.rowCount) return res.status(404).json({ error: 'Active assignment not found' }); res.json({ removed: true }); });
  return router;
}
module.exports = { verifyAssertion, createGhlEmbeddedRouter, createActivationRouter, createAssignmentRouter };
