const crypto = require('node:crypto');
const express = require('express');
const { verifyGhl, GHL_ED25519_PUBLIC_KEY } = require('./signatures');
const { CredentialVault } = require('../connectors/vault');
const { MessagingRepository } = require('../messaging/repository');
const { createMessagingRuntime } = require('../messaging/runtime');

const DEFAULT_AUTH_URL = 'https://marketplace.gohighlevel.com/oauth/chooselocation';
const DEFAULT_TOKEN_URL = 'https://services.leadconnectorhq.com/oauth/token';
const DEFAULT_API_URL = 'https://services.leadconnectorhq.com';
const DEFAULT_SCOPES = ['conversations.read', 'conversations.write', 'contacts.read', 'locations.read'];

class GhlPilotError extends Error { constructor(code, message = 'HighLevel private pilot request failed', status = 400) { super(message); this.code = code; this.status = status; } }
function hashState(value) { return crypto.createHash('sha256').update(String(value)).digest('hex'); }
function randomId(prefix) { return `${prefix}-${crypto.randomUUID()}`; }
function scopes(value) { return [...new Set(Array.isArray(value) ? value.map(String) : String(value || '').split(/[ ,]+/).filter(Boolean))]; }
function config(env = process.env) { return { clientId: String(env.GHL_CLIENT_ID || ''), clientSecret: String(env.GHL_CLIENT_SECRET || ''), redirectUri: String(env.GHL_REDIRECT_URI || `${env.APP_ORIGIN || ''}/oauth/highlevel/callback`), authUrl: String(env.GHL_AUTH_URL || DEFAULT_AUTH_URL), tokenUrl: String(env.GHL_TOKEN_URL || DEFAULT_TOKEN_URL), apiUrl: String(env.GHL_API_BASE_URL || DEFAULT_API_URL).replace(/\/$/, ''), requiredScopes: scopes(env.GHL_REQUIRED_SCOPES || DEFAULT_SCOPES), publicKey: env.GHL_PUBLIC_KEY || GHL_ED25519_PUBLIC_KEY, appOrigin: String(env.APP_ORIGIN || '') }; }
function safeProviderError(error) { return new GhlPilotError(error?.code || 'GHL_PROVIDER_UNAVAILABLE', 'HighLevel service is temporarily unavailable', 503); }

class GhlPilotRepository {
  constructor(pool, vault, now = () => new Date()) { if (!pool || !vault) throw new TypeError('HighLevel repository requires a pool and credential vault'); this.pool = pool; this.vault = vault; this.now = now; }
  async createState({ userId, workspaceId, ttlMs = 10 * 60 * 1000 }) { const raw = crypto.randomBytes(32).toString('base64url'); await this.pool.query('INSERT INTO ghl_oauth_states(id,state_hash,user_id,workspace_id,expires_at) VALUES($1,$2,$3,$4,now()+($5*interval \'1 millisecond\'))',[randomId('ghl-state'),hashState(raw),userId,workspaceId,ttlMs]); return raw; }
  async claimState({ rawState, userId }) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const result = await client.query('SELECT * FROM ghl_oauth_states WHERE state_hash=$1 AND user_id=$2 FOR UPDATE',[hashState(rawState),userId]); const row=result.rows[0]; if(!row || row.used_at || new Date(row.expires_at)<=this.now()) { await client.query('ROLLBACK'); return null; } await client.query('UPDATE ghl_oauth_states SET used_at=now() WHERE id=$1',[row.id]); await client.query('COMMIT'); return row; } catch(error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async upsertInstallation({ workspaceId, installationId, companyId, locationId, credentials, scopes: grantedScopes, expiresAt }) { const id=randomId('ghl-installation'); const secret=this.vault.encrypt(credentials,id); const result=await this.pool.query(`INSERT INTO ghl_installations(id,installation_id,company_id,location_id,workspace_id,encrypted_credentials,encryption_key_id,scopes,access_token_expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(installation_id,location_id) DO UPDATE SET company_id=EXCLUDED.company_id,workspace_id=EXCLUDED.workspace_id,encrypted_credentials=EXCLUDED.encrypted_credentials,encryption_key_id=EXCLUDED.encryption_key_id,scopes=EXCLUDED.scopes,access_token_expires_at=EXCLUDED.access_token_expires_at,status='active',updated_at=now() RETURNING *`,[id,installationId,companyId||null,locationId,workspaceId,secret.ciphertext,secret.keyId,grantedScopes,expiresAt]); return this.public(result.rows[0]); }
  public(row) { return row ? { id:row.id,installationId:row.installation_id,companyId:row.company_id,locationId:row.location_id,workspaceId:row.workspace_id,scopes:row.scopes,status:row.status,accessTokenExpiresAt:row.access_token_expires_at,hasCredentials:Boolean(row.encrypted_credentials),keyId:row.encryption_key_id } : null; }
  async getInstallation({ workspaceId, installationId, locationId }) { const result=await this.pool.query('SELECT * FROM ghl_installations WHERE workspace_id=$1 AND installation_id=$2 AND location_id=$3 AND status<>\'revoked\'',[workspaceId,installationId,locationId]); return result.rows[0]||null; }
  async getAccessToken({ installationId, locationId, refresh }) { const client=await this.pool.connect(); try { await client.query('BEGIN'); const result=await client.query('SELECT * FROM ghl_installations WHERE installation_id=$1 AND location_id=$2 AND status<>\'revoked\' FOR UPDATE',[installationId,locationId]); const row=result.rows[0]; if(!row) throw new GhlPilotError('GHL_INSTALLATION_NOT_FOUND','HighLevel installation mapping not found',404); let credentials=this.vault.decrypt(row.encrypted_credentials,row.id,row.encryption_key_id); if(new Date(row.access_token_expires_at)>new Date(this.now().getTime()+60000)) { await client.query('COMMIT'); return { accessToken:credentials.accessToken, row }; } if(!credentials.refreshToken) throw new GhlPilotError('GHL_RECONNECT_REQUIRED','HighLevel reconnect is required',409); const rotated=await refresh(credentials.refreshToken); if(!rotated?.accessToken) throw new GhlPilotError('GHL_REFRESH_FAILED','HighLevel token refresh failed',503); credentials={...credentials,accessToken:rotated.accessToken,refreshToken:rotated.refreshToken||credentials.refreshToken,tokenType:rotated.tokenType||credentials.tokenType}; const secret=this.vault.encrypt(credentials,row.id); const expiresAt=new Date(this.now().getTime()+Number(rotated.expiresIn||3600)*1000); await client.query('UPDATE ghl_installations SET encrypted_credentials=$1,encryption_key_id=$2,access_token_expires_at=$3,updated_at=now(),status=\'active\' WHERE id=$4',[secret.ciphertext,secret.keyId,expiresAt,row.id]); await client.query('COMMIT'); return {accessToken:credentials.accessToken,row:{...row,access_token_expires_at:expiresAt}}; } catch(error) { try{await client.query('ROLLBACK');}catch{} throw error; } finally { client.release(); } }
  async mapNumber({ workspaceId, installationId, locationId, whatsappNumberId, providerConnectionId }) { const result=await this.pool.query(`INSERT INTO ghl_number_mappings(id,installation_id,workspace_id,location_id,whatsapp_number_id,provider_connection_id) SELECT $1,i.id,i.workspace_id,i.location_id,$5,$6 FROM ghl_installations i JOIN whatsapp_numbers n ON n.id=$5 AND n.workspace_id=$2 AND n.provider_connection_id=$6 JOIN provider_connections p ON p.id=$6 AND p.workspace_id=$2 AND p.status='active' WHERE i.workspace_id=$2 AND i.installation_id=$3 AND i.location_id=$4 ON CONFLICT(installation_id,location_id) DO UPDATE SET whatsapp_number_id=EXCLUDED.whatsapp_number_id,provider_connection_id=EXCLUDED.provider_connection_id,updated_at=now() RETURNING *`,[randomId('ghl-map'),workspaceId,installationId,locationId,whatsappNumberId,providerConnectionId]); if(!result.rowCount) throw new GhlPilotError('GHL_MAPPING_INVALID','Exact workspace, location, WhatsApp number, and active provider connection are required',409); return result.rows[0]; }
  async resolveMapping({ installationId, locationId, workspaceId, whatsappNumberId }) { const result=await this.pool.query(`SELECT m.*,i.company_id,i.encrypted_credentials,i.encryption_key_id,i.access_token_expires_at,i.scopes,p.provider,p.status provider_status,n.automation_enabled FROM ghl_number_mappings m JOIN ghl_installations i ON i.id=m.installation_id AND i.status='active' JOIN whatsapp_numbers n ON n.id=m.whatsapp_number_id AND n.workspace_id=m.workspace_id AND n.provider_connection_id=m.provider_connection_id JOIN provider_connections p ON p.id=m.provider_connection_id AND p.workspace_id=m.workspace_id WHERE i.installation_id=$1 AND i.location_id=$2 AND m.workspace_id=$3 AND ($4::text IS NULL OR m.whatsapp_number_id=$4)`,[installationId,locationId,workspaceId,whatsappNumberId||null]); if(result.rowCount!==1) throw new GhlPilotError('GHL_MAPPING_NOT_FOUND','Exact HighLevel location mapping was not found',404); return result.rows[0]; }
  async linkConversation({ mapping, conversationId, ghlConversationId, ghlContactId }) { const result=await this.pool.query(`INSERT INTO ghl_conversation_links(id,mapping_id,installation_id,location_id,workspace_id,ghl_conversation_id,ghl_contact_id,conversation_id,whatsapp_number_id,provider_connection_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(installation_id,location_id,ghl_conversation_id) DO UPDATE SET ghl_contact_id=EXCLUDED.ghl_contact_id,conversation_id=EXCLUDED.conversation_id,updated_at=now() RETURNING *`,[randomId('ghl-link'),mapping.id,mapping.installation_id,mapping.location_id,mapping.workspace_id,ghlConversationId,ghlContactId||null,conversationId,mapping.whatsapp_number_id,mapping.provider_connection_id]); return result.rows[0]; }
  async conversation({ mapping, ghlConversationId }) { const result=await this.pool.query('SELECT * FROM ghl_conversation_links WHERE mapping_id=$1 AND ghl_conversation_id=$2',[mapping.id,ghlConversationId]); return result.rows[0]||null; }
  async claimCorrelation({ mapping, ghlMessageId, direction, conversationId, contactId }) { const result=await this.pool.query(`INSERT INTO ghl_message_correlations(id,mapping_id,installation_id,location_id,workspace_id,whatsapp_number_id,provider_connection_id,ghl_message_id,ghl_conversation_id,ghl_contact_id,direction) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(installation_id,location_id,ghl_message_id) DO NOTHING RETURNING *`,[randomId('ghl-correlation'),mapping.id,mapping.installation_id,mapping.location_id,mapping.workspace_id,mapping.whatsapp_number_id,mapping.provider_connection_id,ghlMessageId,conversationId||null,contactId||null,direction]); if(result.rowCount)return{created:true,row:result.rows[0]}; const existing=await this.pool.query('SELECT * FROM ghl_message_correlations WHERE installation_id=$1 AND location_id=$2 AND ghl_message_id=$3',[mapping.installation_id,mapping.location_id,ghlMessageId]); return{created:false,row:existing.rows[0]}; }
  async completeCorrelation(id,values) { const result=await this.pool.query('UPDATE ghl_message_correlations SET canonical_message_id=COALESCE($1,canonical_message_id),provider_message_id=COALESCE($2,provider_message_id),status=$3,error_code=NULL,updated_at=now() WHERE id=$4 RETURNING *',[values.canonicalMessageId||null,values.providerMessageId||null,values.status||'sent',id]); return result.rows[0]; }
  async failCorrelation(id,code) { await this.pool.query('UPDATE ghl_message_correlations SET status=\'failed\',error_code=$1,updated_at=now() WHERE id=$2',[String(code||'GHL_DELIVERY_FAILED').slice(0,100),id]); }
  async revoke({workspaceId,installationId}) { const client=await this.pool.connect(); try { await client.query('BEGIN'); await client.query('DELETE FROM ghl_number_mappings WHERE installation_id IN (SELECT id FROM ghl_installations WHERE workspace_id=$1 AND installation_id=$2)',[workspaceId,installationId]); const result=await client.query('UPDATE ghl_installations SET encrypted_credentials=\'\\x\',status=\'revoked\',updated_at=now() WHERE workspace_id=$1 AND installation_id=$2 RETURNING id,installation_id,location_id,workspace_id,status',[workspaceId,installationId]); await client.query('COMMIT'); return result.rows[0]||null; } catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();} }
}

class GhlApiClient {
  constructor(env=process.env,fetchImpl=globalThis.fetch){this.config=config(env);this.fetchImpl=fetchImpl;}
  async tokenRequest(body){const response=await this.fetchImpl(this.config.tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...body,client_id:this.config.clientId,client_secret:this.config.clientSecret}).toString()});let data={};try{data=await response.json();}catch{}if(!response.ok||!data.access_token)throw new GhlPilotError('GHL_TOKEN_EXCHANGE_FAILED','HighLevel token exchange failed',502);return{accessToken:data.access_token,refreshToken:data.refresh_token,expiresIn:Number(data.expires_in||3600),tokenType:data.token_type||'Bearer',scopes:scopes(data.scope)};}
  exchangeCode(code){return this.tokenRequest({grant_type:'authorization_code',code,redirect_uri:this.config.redirectUri});}
  refreshToken(refreshToken){return this.tokenRequest({grant_type:'refresh_token',refresh_token:refreshToken});}
  async sendMessage({accessToken,locationId,conversationId,contactId,message,idempotencyKey}){const response=await this.fetchImpl(`${this.config.apiUrl}/conversations/messages`,{method:'POST',headers:{authorization:`Bearer ${accessToken}`,'content-type':'application/json','x-idempotency-key':idempotencyKey},body:JSON.stringify({locationId,conversationId,contactId,type:'SMS',message})});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new GhlPilotError('GHL_MESSAGE_DELIVERY_FAILED','HighLevel message delivery failed',502);return{externalMessageId:String(data.messageId||data.id||idempotencyKey),raw:data};}
}

function authUser(req,store){const user=req.session?.userId&&store.findUser(req.session.userId);return user&&user.active?user:null;}
function jsonError(res,error){const e=error instanceof GhlPilotError?error:safeProviderError(error);return res.status(e.status||503).json({error:e.message,code:e.code});}
function createGhlPrivatePilotRuntime({store,env=process.env,fetchImpl=globalThis.fetch}){const expressApp=express; if(store?.driver!=='postgres'||!store.repository?.pool||!env.CONNECTOR_MASTER_KEY)return{oauthRouter:expressApp.Router(),apiRouter:expressApp.Router(),messagesRouter:expressApp.Router(),eventsRouter:expressApp.Router(),enabled:false};const vault=new CredentialVault({env});const repository=new GhlPilotRepository(store.repository.pool,vault);const client=new GhlApiClient(env,fetchImpl);const messagingRepository=new MessagingRepository(store.repository.pool);const messagingService=createMessagingRuntime({pool:store.repository.pool,env,vault,fetchImpl});const oauthRouter=expressApp.Router();const apiRouter=expressApp.Router();const messagesRouter=expressApp.Router();const eventsRouter=expressApp.Router();
  oauthRouter.get('/start',async(req,res)=>{try{const user=authUser(req,store);const workspaceId=String(req.query.workspaceId||'');if(!user||!store.canManageWorkspace(user,workspaceId))return res.status(404).json({error:'Workspace not found'});const c=config(env);if(!c.clientId||!c.clientSecret||!c.redirectUri)return res.status(503).json({error:'HighLevel OAuth is not configured',code:'GHL_OAUTH_NOT_CONFIGURED'});const state=await repository.createState({userId:user.id,workspaceId});const url=new URL(c.authUrl);url.searchParams.set('response_type','code');url.searchParams.set('client_id',c.clientId);url.searchParams.set('redirect_uri',c.redirectUri);url.searchParams.set('scope',c.requiredScopes.join(' '));url.searchParams.set('state',state);res.redirect(url.toString());}catch(error){jsonError(res,error);}});
  oauthRouter.get('/callback',async(req,res)=>{try{const user=authUser(req,store);const code=String(req.query.code||'');const state=String(req.query.state||'');if(!user||!code||!state)return res.status(400).json({error:'HighLevel OAuth callback is invalid'});const claimed=await repository.claimState({rawState:state,userId:user.id});if(!claimed)return res.status(400).json({error:'HighLevel OAuth state is expired or already used'});const token=await client.exchangeCode(code);const c=config(env);const granted=token.scopes.length?token.scopes:c.requiredScopes;if(c.requiredScopes.some(scope=>!granted.includes(scope)))return res.status(400).json({error:'HighLevel OAuth scopes are insufficient',code:'GHL_SCOPES_INSUFFICIENT'});const locationId=String(req.query.locationId||'');const companyId=String(req.query.companyId||'');const installationId=String(req.query.installationId||`${companyId||'company'}:${locationId||'location'}`);if(!locationId)return res.status(400).json({error:'HighLevel location binding is required',code:'GHL_LOCATION_REQUIRED'});await repository.upsertInstallation({workspaceId:claimed.workspace_id,installationId,companyId,locationId,credentials:{accessToken:token.accessToken,refreshToken:token.refreshToken,tokenType:token.tokenType},scopes:granted,expiresAt:new Date(Date.now()+token.expiresIn*1000)});const target=c.appOrigin?`${c.appOrigin.replace(/\/$/,'')}/settings/integrations?ghl=connected`:'/';res.redirect(target);}catch(error){jsonError(res,error);}});
  const requireManage=async(req,res,next)=>{const user=authUser(req,store);if(!user)return res.status(401).json({error:'Please sign in'});const workspaceId=String(req.body?.workspaceId||req.query.workspaceId||'');if(!store.canManageWorkspace(user,workspaceId))return res.status(404).json({error:'Workspace not found'});req.ghlUser=user;req.ghlWorkspaceId=workspaceId;next();};
  apiRouter.get('/diagnostics',requireManage,async(req,res)=>{try{const row=await repository.getInstallation({workspaceId:req.ghlWorkspaceId,installationId:String(req.query.installationId||''),locationId:String(req.query.locationId||'')});if(!row)return res.status(404).json({error:'HighLevel installation not found'});res.json(repository.public(row));}catch(error){jsonError(res,error);}});
  apiRouter.post('/mappings',requireManage,async(req,res)=>{try{const mapping=await repository.mapNumber({workspaceId:req.ghlWorkspaceId,installationId:String(req.body.installationId),locationId:String(req.body.locationId),whatsappNumberId:String(req.body.whatsappNumberId),providerConnectionId:String(req.body.providerConnectionId)});res.status(201).json({mapping:{id:mapping.id,workspaceId:mapping.workspace_id,locationId:mapping.location_id,whatsappNumberId:mapping.whatsapp_number_id,providerConnectionId:mapping.provider_connection_id}});}catch(error){jsonError(res,error);}});
  apiRouter.post('/revoke',requireManage,async(req,res)=>{try{const result=await repository.revoke({workspaceId:req.ghlWorkspaceId,installationId:String(req.body.installationId)});if(!result)return res.status(404).json({error:'HighLevel installation not found'});res.json({revoked:true,installationId:result.installation_id,locationId:result.location_id});}catch(error){jsonError(res,error);}});
  const verifyWebhook=expressApp.raw({type:'application/json',limit:'256kb'});
  messagesRouter.post('/',verifyWebhook,async(req,res)=>{try{const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from('');if(!verifyGhl(raw,req.get('x-ghl-signature'),config(env).publicKey))return res.status(401).json({error:'Invalid provider signature'});let body;try{body=JSON.parse(raw.toString('utf8'));}catch{throw new GhlPilotError('GHL_PAYLOAD_INVALID','Invalid HighLevel message payload',400);}const installationId=String(body.installationId||body.appId||'');const locationId=String(body.locationId||'');const workspaceId=String(body.workspaceId||'');if(!installationId||!locationId||!workspaceId)throw new GhlPilotError('GHL_MAPPING_REQUIRED','Installation, location, and workspace mapping are required',409);const mapping=await repository.resolveMapping({installationId,locationId,workspaceId,whatsappNumberId:body.whatsappNumberId});const ghlMessageId=String(body.messageId||body.id||'');if(!ghlMessageId)throw new GhlPilotError('GHL_MESSAGE_ID_REQUIRED','GHL message ID is required',400);const claim=await repository.claimCorrelation({mapping,ghlMessageId,direction:'outbound',conversationId:body.conversationId,contactId:body.contactId});if(!claim.created)return res.json({duplicate:true,correlationId:claim.row.id,status:claim.row.status});let conversation=body.canonicalConversationId?{id:body.canonicalConversationId}:await repository.conversation({mapping,ghlConversationId:String(body.conversationId||'')});if(!conversation&&body.contactPhone){const id=await messagingRepository.resolveOrCreateConversation({workspaceId:mapping.workspace_id,numberId:mapping.whatsapp_number_id,phone:body.contactPhone});if(id){conversation={id};await repository.linkConversation({mapping,conversationId:id,ghlConversationId:String(body.conversationId),ghlContactId:body.contactId});}}if(!conversation)throw new GhlPilotError('GHL_CONVERSATION_NOT_MAPPED','GHL conversation is not mapped to the exact WhatsApp number',409);const result=await messagingService.sendText({actorId:null,workspaceIds:[mapping.workspace_id],conversationId:conversation.id,text:String(body.message||body.body||''),idempotencyKey:`ghl:${mapping.id}:${ghlMessageId}`,origin:'crm'});await repository.completeCorrelation(claim.row.id,{canonicalMessageId:result.message?.id,providerMessageId:result.message?.externalMessageId,status:'sent'});res.status(result.duplicate?200:202).json({accepted:true,duplicate:Boolean(result.duplicate),correlationId:claim.row.id});}catch(error){if(error instanceof GhlPilotError&&error.code.startsWith('GHL_'))return jsonError(res,error);jsonError(res,error);}});
  eventsRouter.post('/',verifyWebhook,async(req,res)=>{try{const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from('');if(!verifyGhl(raw,req.get('x-ghl-signature'),config(env).publicKey))return res.status(401).json({error:'Invalid provider signature'});let body;try{body=JSON.parse(raw.toString('utf8'));}catch{throw new GhlPilotError('GHL_PAYLOAD_INVALID','Invalid HighLevel event payload',400);}if(String(body.type||'').toLowerCase().includes('uninstall')){const user=authUser(req,store);if(user&&body.workspaceId)await repository.revoke({workspaceId:String(body.workspaceId),installationId:String(body.installationId||'')});}res.status(202).json({accepted:true});}catch(error){jsonError(res,error);}});
  return {oauthRouter,apiRouter,messagesRouter,eventsRouter,repository,client,deliverInboundWhatsApp:async({mapping,conversationId,contactId,body,canonicalMessageId,providerMessageId,ghlMessageId})=>{const correlation=await repository.claimCorrelation({mapping,ghlMessageId:ghlMessageId||`wa:${providerMessageId||canonicalMessageId}`,direction:'inbound',conversationId,contactId});if(!correlation.created)return{duplicate:true,correlationId:correlation.row.id};try{const token=await repository.getAccessToken({installationId:mapping.installation_id,locationId:mapping.location_id,refresh(value){return client.refreshToken(value);}});const sent=await client.sendMessage({accessToken:token.accessToken,locationId:mapping.location_id,conversationId,contactId,message:body,idempotencyKey:`wa:${providerMessageId||canonicalMessageId}`});await repository.completeCorrelation(correlation.row.id,{canonicalMessageId,providerMessageId,status:'sent'});return{duplicate:false,correlationId:correlation.row.id,ghlMessageId:sent.externalMessageId};}catch(error){await repository.failCorrelation(correlation.row.id,error.code||'GHL_INBOUND_FAILED');throw safeProviderError(error);}}};}
module.exports={GhlPilotError,GhlPilotRepository,GhlApiClient,createGhlPrivatePilotRuntime,config,hashState};
