const crypto=require("node:crypto");const express=require("express");
function equal(a,b){const x=Buffer.from(String(a||"")),y=Buffer.from(String(b||""));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y);}
function createConnectorRouter({store,repository,requireAuth}){const router=express.Router();const ids=req=>store.listWorkspaces(req.user).map(w=>w.id);const manage=(req,res,workspaceId)=>{if(!store.canManageWorkspace(req.user,workspaceId)){res.status(404).json({error:"Workspace not found"});return false;}return true;};
  router.post("/:id/webhook",async(req,res)=>{const connection=await repository.internal(req.params.id);if(!connection||connection.status==='revoked')return res.status(404).json({error:"Connector not found"});try{const credentials=repository.credentials(connection);const expected=crypto.createHmac("sha256",String(credentials.webhookSecret)).update(req.rawBody||Buffer.from(JSON.stringify(req.body))).digest("hex");if(!equal(req.get("x-connector-signature"),expected))return res.status(401).json({error:"Invalid connector signature"});const result=await repository.receive(connection,req.body);res.status(result.duplicate?200:202).json(result);}catch(error){res.status(422).json({error:error.message});}});
  router.use(requireAuth);router.get("/",async(req,res)=>res.json({connections:await repository.list(ids(req))}));
  router.post("/",async(req,res)=>{const workspaceId=String(req.body.workspaceId||"");if(!manage(req,res,workspaceId))return;const provider=String(req.body.provider||"");if(!["shopify","ghl","woocommerce","generic"].includes(provider))return res.status(400).json({error:"Unsupported connector provider"});const credentials=req.body.credentials;let baseUrl;try{baseUrl=new URL(String(credentials?.baseUrl));}catch{return res.status(400).json({error:"Valid HTTPS connector base URL is required"});}if(baseUrl.protocol!=="https:"||!credentials.token||!credentials.webhookSecret)return res.status(400).json({error:"HTTPS base URL, connector token and webhook secret are required"});try{const connection=await repository.install({workspaceId,provider,label:String(req.body.label||provider).trim().slice(0,120)||provider,credentials,scopes:Array.isArray(req.body.scopes)?req.body.scopes:[],fieldMapping:req.body.fieldMapping||{},conflictPolicy:["source_wins","latest_wins","manual_review"].includes(req.body.conflictPolicy)?req.body.conflictPolicy:"latest_wins"});await store.addAudit(req.user.id,"connector.installed",{workspaceId,connectionId:connection.id,provider,scopes:connection.scopes});res.status(201).json({connection});}catch(error){res.status(400).json({error:error.message});}});
  router.patch("/:id/settings",async(req,res)=>{const existing=await repository.get(ids(req),req.params.id);if(!existing||!manage(req,res,existing.workspaceId))return;const connection=await repository.updateSettings(ids(req),existing.id,{scopes:Array.isArray(req.body.scopes)?req.body.scopes:existing.scopes,fieldMapping:req.body.fieldMapping||existing.fieldMapping,conflictPolicy:["source_wins","latest_wins","manual_review"].includes(req.body.conflictPolicy)?req.body.conflictPolicy:existing.conflictPolicy});res.json({connection});});
  router.post("/:id/rotate",async(req,res)=>{const existing=await repository.get(ids(req),req.params.id);if(!existing||!manage(req,res,existing.workspaceId))return;if(!req.body.credentials?.token||!req.body.credentials?.webhookSecret)return res.status(400).json({error:"Connector token and webhook secret are required"});const connection=await repository.rotate(ids(req),existing.id,req.body.credentials);await store.addAudit(req.user.id,"connector.credentials.rotated",{workspaceId:existing.workspaceId,connectionId:existing.id,keyId:connection.keyId});res.json({connection});});
  router.post("/:id/replay",async(req,res)=>{const existing=await repository.get(ids(req),req.params.id);if(!existing||!manage(req,res,existing.workspaceId))return;const replay=await repository.replay(ids(req),existing.id);await store.addAudit(req.user.id,"connector.replayed",{workspaceId:existing.workspaceId,connectionId:existing.id,...replay});res.json({replay});});
  router.get("/:id/diagnostics",async(req,res)=>{const result=await repository.diagnostics(ids(req),req.params.id);if(!result)return res.status(404).json({error:"Connector not found"});res.json(result);});
  router.delete("/:id",async(req,res)=>{const existing=await repository.get(ids(req),req.params.id);if(!existing||!manage(req,res,existing.workspaceId))return;const connection=await repository.revoke(ids(req),existing.id);await store.addAudit(req.user.id,"connector.revoked",{workspaceId:existing.workspaceId,connectionId:existing.id});res.json({connection});});return router;}
module.exports={createConnectorRouter,equal};
