const crypto=require("node:crypto");
const {renderTemplate}=require("./policy");

class CampaignRepository {
  constructor(pool){this.pool=pool;}
  ids(workspaceIds){return workspaceIds?.length?workspaceIds.map(String):["__none__"];}
  async create({workspaceId,numberId,name,template,scheduledAt,quietStart,quietEnd,createdBy,contacts}){
    const client=await this.pool.connect();const id=crypto.randomUUID();
    try{await client.query("BEGIN");const number=await client.query("SELECT 1 FROM whatsapp_numbers WHERE id=$1 AND workspace_id=$2",[numberId,workspaceId]);if(!number.rowCount)throw new Error("WhatsApp number not found in workspace");
      const initialStatus=scheduledAt?'scheduled':'draft';await client.query(`INSERT INTO campaigns(id,workspace_id,whatsapp_number_id,name,template,status,scheduled_at,quiet_start,quiet_end,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,workspaceId,numberId,name,template,initialStatus,scheduledAt||null,quietStart??null,quietEnd??null,createdBy]);
      let accepted=0,rejected=0;
      for(const input of contacts){const contactId=crypto.randomUUID();await client.query(`INSERT INTO contacts(id,workspace_id,phone_e164,display_name) VALUES($1,$2,$3,$4) ON CONFLICT(workspace_id,phone_e164) DO UPDATE SET display_name=COALESCE(NULLIF(EXCLUDED.display_name,''),contacts.display_name)`,[contactId,workspaceId,input.phone,input.name||null]);const contact=await client.query("SELECT id,phone_e164,display_name FROM contacts WHERE workspace_id=$1 AND phone_e164=$2",[workspaceId,input.phone]);
        await client.query(`INSERT INTO consent_records(id,workspace_id,contact_id,purpose,status,source,policy_version,evidence,captured_at) VALUES($1,$2,$3,'campaign','granted',$4,$5,$6,$7)`,[crypto.randomUUID(),workspaceId,contact.rows[0].id,input.consentSource,input.policyVersion,{importEvidence:input.evidence||null},input.consentCapturedAt]);
        const blocked=await client.query(`SELECT 1 FROM suppressions WHERE phone_e164=$1 AND (scope='global' OR workspace_id=$2) LIMIT 1`,[input.phone,workspaceId]);const status=blocked.rowCount?'suppressed':'pending';if(blocked.rowCount)rejected++;else accepted++;
        const recipientId=crypto.randomUUID();await client.query(`INSERT INTO campaign_recipients(id,workspace_id,campaign_id,contact_id,personalized_body,status) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(campaign_id,contact_id) DO NOTHING`,[recipientId,workspaceId,id,contact.rows[0].id,renderTemplate(template,{name:input.name,phone:input.phone}),status]);await client.query(`INSERT INTO campaign_recipient_events(id,workspace_id,campaign_id,recipient_id,to_status,reason) SELECT $1,$2,$3,$4,$5,$6 WHERE EXISTS(SELECT 1 FROM campaign_recipients WHERE id=$4)`,[crypto.randomUUID(),workspaceId,id,recipientId,status,blocked.rowCount?'suppression_match':'imported']);}
      await client.query("COMMIT");return{id,workspaceId,status:initialStatus,accepted,rejected,total:contacts.length};
    }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
  }
  async list(workspaceIds){const r=await this.pool.query(`SELECT c.*,COUNT(r.id)::int AS total,COUNT(*) FILTER(WHERE r.status IN('pending','processing'))::int AS pending,COUNT(*) FILTER(WHERE r.status IN('sent','delivered','read'))::int AS sent,COUNT(*) FILTER(WHERE r.status IN('failed','dead_letter'))::int AS failed,COUNT(*) FILTER(WHERE r.status IN('suppressed','unconsented'))::int AS blocked FROM campaigns c LEFT JOIN campaign_recipients r ON r.campaign_id=c.id WHERE c.workspace_id=ANY($1::text[]) GROUP BY c.id ORDER BY c.created_at DESC`,[this.ids(workspaceIds)]);return r.rows;}
  async get(workspaceIds,id){const r=await this.pool.query("SELECT * FROM campaigns WHERE id=$1 AND workspace_id=ANY($2::text[])",[id,this.ids(workspaceIds)]);return r.rows[0]||null;}
  async setStatus(workspaceIds,id,status){const r=await this.pool.query("UPDATE campaigns SET status=$1,updated_at=now() WHERE id=$2 AND workspace_id=ANY($3::text[]) AND status NOT IN('cancelled','completed') RETURNING *",[status,id,this.ids(workspaceIds)]);if(status==='cancelled'&&r.rowCount){const cancelled=await this.pool.query("UPDATE campaign_recipients SET status='cancelled',updated_at=now() WHERE campaign_id=$1 AND status='pending' RETURNING *",[id]);for(const row of cancelled.rows)await this.event(row,"pending","cancelled","campaign_cancelled");}return r.rows[0]||null;}
  async suppress({workspaceId,phone,contactId=null,scope='workspace',reason}){const id=crypto.randomUUID();const r=await this.pool.query(`INSERT INTO suppressions(id,workspace_id,contact_id,phone_e164,scope,reason) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING *`,[id,scope==='global'?null:workspaceId,contactId,phone,scope,reason]);const blocked=await this.pool.query(`UPDATE campaign_recipients cr SET status='suppressed',last_error=$3,updated_at=now() FROM contacts c WHERE cr.contact_id=c.id AND c.phone_e164=$1 AND cr.status='pending' AND ($2::text IS NULL OR cr.workspace_id=$2) RETURNING cr.*`,[phone,scope==='global'?null:workspaceId,reason]);for(const row of blocked.rows)await this.event(row,"pending","suppressed",reason);return r.rows[0]||{phone_e164:phone,scope};}
  async listSuppressions(workspaceIds){const r=await this.pool.query("SELECT * FROM suppressions WHERE scope='global' OR workspace_id=ANY($1::text[]) ORDER BY created_at DESC",[this.ids(workspaceIds)]);return r.rows;}
  async claim(){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("UPDATE campaigns SET status='running',updated_at=now() WHERE status='scheduled' AND scheduled_at<=now()");const r=await client.query(`SELECT cr.*,c.whatsapp_number_id,c.status AS campaign_status,c.quiet_start,c.quiet_end,ct.phone_e164 FROM campaign_recipients cr JOIN campaigns c ON c.id=cr.campaign_id JOIN contacts ct ON ct.id=cr.contact_id WHERE cr.status='pending' AND cr.next_attempt_at<=now() AND c.status='running' AND (c.scheduled_at IS NULL OR c.scheduled_at<=now()) ORDER BY cr.next_attempt_at,cr.created_at FOR UPDATE OF cr SKIP LOCKED LIMIT 1`);if(!r.rowCount){await client.query("COMMIT");return null;}await client.query("UPDATE campaign_recipients SET status='processing',attempt_count=attempt_count+1,updated_at=now() WHERE id=$1",[r.rows[0].id]);await client.query("INSERT INTO campaign_recipient_events(id,workspace_id,campaign_id,recipient_id,from_status,to_status,reason) VALUES($1,$2,$3,$4,'pending','processing','worker_claimed')",[crypto.randomUUID(),r.rows[0].workspace_id,r.rows[0].campaign_id,r.rows[0].id]);await client.query("COMMIT");return{...r.rows[0],status:"processing",attempt_count:r.rows[0].attempt_count+1};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
  async event(recipient,fromStatus,toStatus,reason,details={}){await this.pool.query("INSERT INTO campaign_recipient_events(id,workspace_id,campaign_id,recipient_id,from_status,to_status,reason,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[crypto.randomUUID(),recipient.workspace_id,recipient.campaign_id,recipient.id,fromStatus,toStatus,reason,details]);}
  async eligibility(recipient){const r=await this.pool.query(`SELECT EXISTS(SELECT 1 FROM consent_records WHERE workspace_id=$1 AND contact_id=$2 AND channel='whatsapp' AND status='granted' AND (expires_at IS NULL OR expires_at>now()) AND captured_at=(SELECT MAX(captured_at) FROM consent_records WHERE workspace_id=$1 AND contact_id=$2 AND channel='whatsapp')) AS consented,EXISTS(SELECT 1 FROM suppressions s JOIN contacts c ON c.phone_e164=s.phone_e164 WHERE c.id=$2 AND (s.scope='global' OR s.workspace_id=$1)) AS suppressed`,[recipient.workspace_id,recipient.contact_id]);return r.rows[0];}
  async transition(recipient,toStatus,reason=null,details={}){const from=recipient.status;await this.pool.query("UPDATE campaign_recipients SET status=$1,last_error=$2,external_message_id=COALESCE($3,external_message_id),updated_at=now() WHERE id=$4",[toStatus,reason,details.externalMessageId||null,recipient.id]);await this.event(recipient,from,toStatus,reason,details);await this.pool.query("UPDATE campaigns SET status='completed',updated_at=now() WHERE id=$1 AND status='running' AND NOT EXISTS(SELECT 1 FROM campaign_recipients WHERE campaign_id=$1 AND status IN('pending','processing'))",[recipient.campaign_id]);}
  async syncDelivery(workspaceId,externalMessageId,status){if(!externalMessageId||!["delivered","read","failed"].includes(status))return null;const existing=await this.pool.query("SELECT * FROM campaign_recipients WHERE workspace_id=$1 AND external_message_id=$2 AND status IN('sent','delivered')",[workspaceId,externalMessageId]);if(!existing.rowCount)return null;await this.transition(existing.rows[0],status,"provider_ack");return{...existing.rows[0],status};}
  async retry(recipient,error,maxAttempts=4){if(recipient.attempt_count>=maxAttempts)return this.transition(recipient,"dead_letter",error);const delay=Math.min(300,2**recipient.attempt_count*5);await this.pool.query("UPDATE campaign_recipients SET status='pending',last_error=$1,next_attempt_at=now()+($2*interval '1 second'),updated_at=now() WHERE id=$3",[error,delay,recipient.id]);await this.pool.query("INSERT INTO campaign_recipient_events(id,workspace_id,campaign_id,recipient_id,from_status,to_status,reason) VALUES($1,$2,$3,$4,'processing','pending',$5)",[crypto.randomUUID(),recipient.workspace_id,recipient.campaign_id,recipient.id,error]);}
  async createApprovedTrigger({workspaceId,numberId,contactId,name,template,createdBy}){const eligible=await this.eligibility({workspace_id:workspaceId,contact_id:contactId});if(!eligible.consented||eligible.suppressed)throw new Error(eligible.suppressed?"Contact is suppressed":"Valid existing consent is required");const contact=(await this.pool.query("SELECT id,display_name,phone_e164 FROM contacts WHERE id=$1 AND workspace_id=$2",[contactId,workspaceId])).rows[0];if(!contact)throw new Error("Contact not found");const number=(await this.pool.query("SELECT id FROM whatsapp_numbers WHERE id=$1 AND workspace_id=$2",[numberId,workspaceId])).rows[0];if(!number)throw new Error("WhatsApp number not found in workspace");if(!template||template.length>4096)throw new Error("Valid message template is required");const campaignId=crypto.randomUUID(),recipientId=crypto.randomUUID();await this.pool.query("INSERT INTO campaigns(id,workspace_id,whatsapp_number_id,name,template,status,created_by) VALUES($1,$2,$3,$4,$5,'running',$6)",[campaignId,workspaceId,numberId,name,template,createdBy]);await this.pool.query("INSERT INTO campaign_recipients(id,workspace_id,campaign_id,contact_id,personalized_body) VALUES($1,$2,$3,$4,$5)",[recipientId,workspaceId,campaignId,contact.id,renderTemplate(template,{name:contact.display_name,phone:contact.phone_e164})]);await this.event({id:recipientId,workspace_id:workspaceId,campaign_id:campaignId},null,"pending","approved_order_trigger");return{id:campaignId,recipientId,status:"running"};}
}
module.exports={CampaignRepository};
