const express=require("express");
const {parseCsv,normalizePhone}=require("./policy");
function createCampaignRouter({store,repository,requireAuth}){const router=express.Router();router.use(requireAuth);const ids=req=>store.listWorkspaces(req.user).map(w=>w.id);const manage=(req,res,workspaceId)=>{if(!store.canManageWorkspace(req.user,workspaceId)){res.status(404).json({error:"Workspace not found"});return false;}return true;};
  router.get("/",async(req,res)=>{try{res.json({campaigns:await repository.list(ids(req))});}catch(e){res.status(500).json({error:e.message});}});
  router.post("/preview",(req,res)=>{try{const contacts=parseCsv(req.body.csv);const unique=[...new Map(contacts.map(c=>[c.phone,c])).values()];res.json({contacts:unique.slice(0,10),total:unique.length,duplicates:contacts.length-unique.length});}catch(e){res.status(400).json({error:e.message});}});
  router.post("/",async(req,res)=>{const workspaceId=String(req.body.workspaceId||"");if(!manage(req,res,workspaceId))return;const name=String(req.body.name||"").trim(),template=String(req.body.template||"").trim();if(name.length<2||name.length>120||!template||template.length>4096)return res.status(400).json({error:"Valid campaign name and message template are required"});try{const parsed=parseCsv(req.body.csv);const contacts=[...new Map(parsed.map(c=>[c.phone,c])).values()];if(!contacts.length||contacts.length>10000)return res.status(400).json({error:"Campaign requires 1 to 10,000 unique contacts"});const campaign=await repository.create({workspaceId,numberId:String(req.body.numberId||""),name,template,scheduledAt:req.body.scheduledAt||null,quietStart:req.body.quietStart===""?null:Number(req.body.quietStart),quietEnd:req.body.quietEnd===""?null:Number(req.body.quietEnd),createdBy:req.user.id,contacts});await store.addAudit(req.user.id,"campaign.created",{workspaceId,campaignId:campaign.id,total:campaign.total,accepted:campaign.accepted,rejected:campaign.rejected});res.status(201).json({campaign});}catch(e){res.status(400).json({error:e.message});}});
  router.patch("/:id/status",async(req,res)=>{const campaign=await repository.get(ids(req),req.params.id);if(!campaign||!manage(req,res,campaign.workspace_id))return;const action=String(req.body.status||"");const allowed={draft:["scheduled","running","cancelled"],scheduled:["running","paused","cancelled"],running:["paused","cancelled"],paused:["running","cancelled"]};if(!allowed[campaign.status]?.includes(action))return res.status(409).json({error:`Cannot change ${campaign.status} campaign to ${action}`});const updated=await repository.setStatus(ids(req),campaign.id,action);await store.addAudit(req.user.id,`campaign.${action}`,{workspaceId:campaign.workspace_id,campaignId:campaign.id});res.json({campaign:updated});});
  router.get("/suppressions",async(req,res)=>{try{res.json({suppressions:await repository.listSuppressions(ids(req))});}catch(e){res.status(500).json({error:e.message});}});
  router.post("/suppressions",async(req,res)=>{const workspaceId=String(req.body.workspaceId||"");if(!manage(req,res,workspaceId))return;const scope=req.body.scope==="global"?"global":"workspace";if(scope==="global"&&req.user.role!=="admin")return res.status(403).json({error:"Administrator access required for global suppression"});const phone=normalizePhone(req.body.phone);if(!phone)return res.status(400).json({error:"Valid phone is required"});const suppression=await repository.suppress({workspaceId,phone,scope,reason:String(req.body.reason||"manual")});await store.addAudit(req.user.id,"contact.suppressed",{workspaceId,phone,scope,reason:suppression.reason});res.status(201).json({suppression});});
  return router;}
module.exports={createCampaignRouter};
