const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { Pool } = require('pg');
const { databaseConfig, assertDatabaseConfig } = require('./config');
const MIGRATIONS = [['001_canonical_schema','docs/schema.sql'],['002_openwa_adapter','docs/migrations/002_openwa_adapter.sql'],['003_unified_inbox','docs/migrations/003_unified_inbox.sql'],['004_safe_campaigns','docs/migrations/004_safe_campaigns.sql'],['005_connector_framework','docs/migrations/005_connector_framework.sql'],['006_provider_connectors','docs/migrations/006_provider_connectors.sql'],['007_canonical_send','docs/migrations/007_canonical_send.sql'],['008_meta_connections','docs/migrations/008_meta_connections.sql'],['009_meta_signup_states','docs/migrations/009_meta_signup_states.sql'],['010_meta_signup_rate_limits','docs/migrations/010_meta_signup_rate_limits.sql'],['011_meta_connection_lifecycle','docs/migrations/011_meta_connection_lifecycle.sql'],['012_meta_webhook_ingestion','docs/migrations/012_meta_webhook_ingestion.sql'],['013_ycloud_provider_foundation','docs/migrations/013_ycloud_provider_foundation.sql'],['014_official_message_templates','docs/migrations/014_official_message_templates.sql'],['015_campaign_template_binding','docs/migrations/015_campaign_template_binding.sql'],['016_media_provider_references','docs/migrations/016_media_provider_references.sql'],['017_meta_media_retention','docs/migrations/017_meta_media_retention.sql'],['018_ghl_private_pilot','docs/migrations/018_ghl_private_pilot.sql'],['019_ghl_conversation_provider','docs/migrations/019_ghl_conversation_provider.sql']].map(([id,file])=>({id,file:path.resolve(__dirname,'..','..',file)}));
function checksum(sql){return crypto.createHash('sha256').update(sql).digest('hex');}
async function runMigrations(pool,migrations=MIGRATIONS){const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock($1)',[90421031]);await client.query('CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())');for(const migration of migrations){const sql=fs.readFileSync(migration.file,'utf8');const hash=checksum(sql);const existing=await client.query('SELECT checksum FROM schema_migrations WHERE id=$1',[migration.id]);if(existing.rowCount){if(existing.rows[0].checksum!==hash)throw new Error(`Applied migration ${migration.id} checksum has changed`);continue;}await client.query(sql);await client.query('INSERT INTO schema_migrations (id,checksum) VALUES($1,$2)',[migration.id,hash]);}await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
async function main(){const config=assertDatabaseConfig({...databaseConfig(),driver:'postgres'});const pool=new Pool(config);try{await runMigrations(pool);console.log(`Applied ${MIGRATIONS.length} PostgreSQL migration(s)`);}finally{await pool.end();}}
if(require.main===module)main().catch(error=>{console.error(error.message);process.exit(1);});
module.exports={MIGRATIONS,checksum,runMigrations};
