function signupError(message, code, status) { const error=new Error(message);error.name="MetaEmbeddedSignupError";error.code=code;if(status)error.providerStatus=status;return error; }
function requireDigits(value,field){const normalized=String(value||"").trim();if(!/^\d+$/.test(normalized))throw signupError(`Valid ${field} is required`,"META_SIGNUP_INVALID");return normalized;}
class MetaEmbeddedSignupService {
  constructor({graphVersion,appId,appSecret,fetchImpl=globalThis.fetch,baseUrl="https://graph.facebook.com"}){this.graphVersion=String(graphVersion||"").trim();this.appId=String(appId||"").trim();this.appSecret=String(appSecret||"").trim();this.fetch=fetchImpl;this.baseUrl=String(baseUrl).replace(/\/$/,"");if(typeof fetchImpl!=="function")throw new TypeError("fetchImpl is required");}
  assertConfigured(){if(!/^v\d+\.\d+$/.test(this.graphVersion)||!this.appId||!this.appSecret)throw signupError("Meta Embedded Signup is not configured","META_SIGNUP_NOT_CONFIGURED");}
  async request(url,options,code){const response=await this.fetch(url,options);let payload=null;try{payload=await response.json();}catch{}if(!response.ok)throw signupError(`Meta Embedded Signup request failed (HTTP ${response.status})`,code,response.status);return payload||{};}
  async exchangeAndVerify({code,businessAccountId,phoneNumberId}){this.assertConfigured();const signupCode=String(code||"").trim();if(!signupCode||signupCode.length>2048)throw signupError("Valid Meta signup code is required","META_SIGNUP_INVALID");const wabaId=requireDigits(businessAccountId,"business account ID");const numberId=requireDigits(phoneNumberId,"phone number ID");const tokenUrl=new URL(`${this.baseUrl}/${this.graphVersion}/oauth/access_token`);tokenUrl.searchParams.set("client_id",this.appId);tokenUrl.searchParams.set("client_secret",this.appSecret);tokenUrl.searchParams.set("code",signupCode);const token=await this.request(tokenUrl,{method:"GET"},"META_CODE_EXCHANGE_FAILED");const accessToken=String(token.access_token||"").trim();if(!accessToken)throw signupError("Meta code exchange returned no access token","META_CODE_EXCHANGE_INVALID");const fields=encodeURIComponent("id,display_phone_number,verified_name");const numbers=await this.request(`${this.baseUrl}/${this.graphVersion}/${wabaId}/phone_numbers?fields=${fields}&limit=100`,{headers:{authorization:`Bearer ${accessToken}`}},"META_NUMBER_VERIFICATION_FAILED");const phone=Array.isArray(numbers.data)?numbers.data.find(item=>String(item.id)===numberId):null;if(!phone)throw signupError("Meta phone number does not belong to the selected business account","META_NUMBER_MAPPING_INVALID");return{accessToken,expiresIn:Number.isFinite(Number(token.expires_in))?Number(token.expires_in):null,businessAccountId:wabaId,phoneNumberId:numberId,displayPhoneNumber:String(phone.display_phone_number||"").trim()||null,verifiedName:String(phone.verified_name||"").trim()||null};}
}
module.exports={MetaEmbeddedSignupService,requireDigits};
