const crypto=require('node:crypto');const{extractMetaEvents,digits}=require('./metaWebhookNormalizer');
function messageType(value){const type=String(value||'text').toLowerCase();return['image','video','audio','document','location','contact','reaction'].includes(type)?type:type==='text'?'text':'other';}
function messageBody(message){return message?.text?.body||message?.image?.caption||message?.video?.caption||message?.document?.caption||message?.button?.text||message?.interactive?.button_reply?.title||message?.interactive?.list_reply?.title||null;}
function occurredAt(value){const number=Number(value);const date=new Date(Number.isFinite(number)&&number>0?number*1000:Date.now());return Number.isNaN(date.getTime())?new Date():date;}
const ranks={queued:0,accepted:1,sent:2,delivered:3,read:4};
function shouldAdvanceStatus(current,next){if(next==='failed')return !['delivered','read'].includes(current);return (ranks[next]??-1)>(ranks[current]??-1);}
class MetaWebhookError extends Error{constructor(message,code){super(message);this.name='MetaWebhookError';this.code=code;}}
class MetaWebhookRepository{
 constructor(pool){if(typeof pool?.query!=='function')throw new TypeError('PostgreSQL pool is required');this.pool=pool;}
 async resolveAsset(event,client=this.pool){const result=await client.query(`SELECT a.workspace_id,p.id AS provider_connection_id,n.id AS number_id FROM meta_connection_assets a JOIN provider_connections p ON p.id=a.provider_connection_id AND p.workspace_id=a.workspace_id JOIN whatsapp_numbers n ON n.provider_connection_id=p.id AND n.workspace_id=p.workspace_id WHERE a.waba_id=$1 AND a.phone_number_id=$2 AND a.disconnected_at IS NULL AND p.provider='whatsapp_cloud' AND p.status IN ('active','degraded')`,[event.wabaId,event.phoneNumberId]);return result.rowCount===1?result.rows[0]:null;}
 async admit(payload){const summary={accepted:0,duplicates:0,unknown:0,invalid:0},events=extractMetaEvents(payload);if(!events.length){summary.invalid=1;return summary;}for(const event of events){const asset=await this.resolveAsset(event);if(!asset){summary.unknown++;continue;}const receipt={kind:event.kind,wabaId:event.wabaId,phoneNumberId:event.phoneNumberId,providerMessageId:event.providerMessageId,status:event.status||null,direction:event.direction||null,echo:Boolean(event.echo),numberId:asset.number_id,value:event.payload};const inserted=await this.pool.query(`INSERT INTO webhook_receipts(id,workspace_id,source,provider_connection_id,external_event_id,signature_valid,payload,status,attempt_count,next_attempt_at) VALUES($1,$2,'meta_whatsapp',$3,$4,true,$5,'received',0,clock_timestamp()) ON CONFLICT(source,provider_connection_id,external_event_id) DO NOTHING RETURNING id`,[crypto.randomUUID(),asset.workspace_id,asset.provider_connection_id,event.externalEventId,receipt]);if(inserted.rowCount)summary.accepted++;else summary.duplicates++;}return summary;}
 async claim(limit=10){const result=await this.pool.query(`WITH picked AS (SELECT id FROM webhook_receipts WHERE source='meta_whatsapp' AND status IN ('received','failed') AND next_attempt_at<=clock_timestamp() ORDER BY received_at FOR UPDATE SKIP LOCKED LIMIT $1) UPDATE webhook_receipts r SET status='processing',attempt_count=attempt_count+1,last_attempt_at=clock_timestamp(),error=NULL FROM picked WHERE r.id=picked.id RETURNING r.*`,[limit]);return result.rows;}
 async processReceipt(receipt){if(typeof this.pool.connect!=='function')throw new TypeError('PostgreSQL transaction support is required');const client=await this.pool.connect();try{await client.query('BEGIN');const payload=receipt.payload||{};const asset=await this.resolveAsset({wabaId:payload.wabaId,phoneNumberId:payload.phoneNumberId},client);if(!asset||asset.workspace_id!==receipt.workspace_id||asset.provider_connection_id!==receipt.provider_connection_id||asset.number_id!==payload.numberId)throw new MetaWebhookError('Meta webhook mapping is unavailable','META_WEBHOOK_MAPPING_UNAVAILABLE');let result;if(payload.kind==='message')result=await this.persistMessage(client,receipt,asset,payload);else if(payload.kind==='status')result=await this.persistStatus(client,receipt,asset,payload);else throw new MetaWebhookError('Unsupported Meta webhook event','META_WEBHOOK_EVENT_UNSUPPORTED');await client.query("UPDATE webhook_receipts SET status='processed',processed_at=clock_timestamp(),error=NULL WHERE id=$1",[receipt.id]);await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
 async persistMessage(client,receipt,asset,payload){const message=payload.value?.message||{},providerMessageId=String(payload.providerMessageId||'');if(!providerMessageId)throw new MetaWebhookError('Meta message identifier is missing','META_MESSAGE_INVALID');const existing=await client.query('SELECT id FROM messages WHERE provider_connection_id=$1 AND external_message_id=$2',[asset.provider_connection_id,providerMessageId]);if(existing.rowCount){if(payload.echo)await client.query(`UPDATE messages SET metadata=metadata||$1::jsonb WHERE id=$2 AND workspace_id=$3`,[{metaEchoObserved:true,metaEchoReceiptId:receipt.id},existing.rows[0].id,asset.workspace_id]);return{duplicate:true,messageId:existing.rows[0].id,echo:Boolean(payload.echo)};}
  const contactPhone=`+${digits(payload.direction==='outbound'?(message.to||payload.value?.contacts?.[0]?.wa_id):message.from)}`;if(!/^\+\d{8,15}$/.test(contactPhone))throw new MetaWebhookError('Meta contact phone is invalid','META_MESSAGE_INVALID');const contactId=crypto.randomUUID();await client.query('INSERT INTO contacts(id,workspace_id,display_name,phone_e164) VALUES($1,$2,$3,$4) ON CONFLICT(workspace_id,phone_e164) DO UPDATE SET display_name=COALESCE(EXCLUDED.display_name,contacts.display_name)',[contactId,asset.workspace_id,payload.value?.contacts?.[0]?.profile?.name||null,contactPhone]);const contact=(await client.query('SELECT id FROM contacts WHERE workspace_id=$1 AND phone_e164=$2',[asset.workspace_id,contactPhone])).rows[0];const conversationId=crypto.randomUUID(),time=occurredAt(message.timestamp);await client.query(`INSERT INTO conversations(id,workspace_id,whatsapp_number_id,contact_id,last_message_at,unread_count) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(workspace_id,whatsapp_number_id,contact_id) DO UPDATE SET last_message_at=GREATEST(COALESCE(conversations.last_message_at,EXCLUDED.last_message_at),EXCLUDED.last_message_at),unread_count=conversations.unread_count+EXCLUDED.unread_count`,[conversationId,asset.workspace_id,asset.number_id,contact.id,time,payload.direction==='inbound'?1:0]);const conversation=(await client.query('SELECT id FROM conversations WHERE workspace_id=$1 AND whatsapp_number_id=$2 AND contact_id=$3',[asset.workspace_id,asset.number_id,contact.id])).rows[0];const id=crypto.randomUUID(),metadata={meta:message,coexistenceEcho:Boolean(payload.echo),webhookReceiptId:receipt.id};const inserted=await client.query(`INSERT INTO messages(id,workspace_id,conversation_id,provider_connection_id,external_message_id,direction,origin,type,body,status,occurred_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(provider_connection_id,external_message_id) WHERE external_message_id IS NOT NULL DO NOTHING RETURNING id`,[id,asset.workspace_id,conversation.id,asset.provider_connection_id,providerMessageId,payload.direction,payload.direction==='outbound'?'phone':'contact',messageType(message.type),messageBody(message),payload.direction==='outbound'?'sent':'received',time,metadata]);const messageId=inserted.rows[0]?.id;if(messageId&&payload.direction==='inbound')await client.query(`INSERT INTO outbox_events(id,workspace_id,event_type,subject_type,subject_id,correlation_id,payload) VALUES($1,$2,'canonical.message.received','message',$3,$4,$5)`,[crypto.randomUUID(),asset.workspace_id,messageId,receipt.id,{messageId,providerConnectionId:asset.provider_connection_id,numberId:asset.number_id,origin:'meta'}]);return{duplicate:!messageId,messageId:messageId||null,echo:Boolean(payload.echo)};}
 async persistStatus(client,receipt,asset,payload){const row=(await client.query('SELECT id,status FROM messages WHERE workspace_id=$1 AND provider_connection_id=$2 AND external_message_id=$3 FOR UPDATE',[asset.workspace_id,asset.provider_connection_id,payload.providerMessageId])).rows[0];if(!row)throw new MetaWebhookError('Canonical message is not ready','META_MESSAGE_NOT_READY');const next=payload.status;if(shouldAdvanceStatus(row.status,next))await client.query('UPDATE messages SET status=$1,metadata=metadata||$2::jsonb WHERE id=$3 AND workspace_id=$4',[next,{lastMetaStatus:payload.value?.status||{}},row.id,asset.workspace_id]);await client.query(`INSERT INTO message_status_events(id,workspace_id,message_id,status,external_event_id,occurred_at,details) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(message_id,external_event_id) WHERE external_event_id IS NOT NULL DO NOTHING`,[crypto.randomUUID(),asset.workspace_id,row.id,next,receipt.external_event_id,occurredAt(payload.value?.status?.timestamp),{meta:payload.value?.status||{},applied:shouldAdvanceStatus(row.status,next)}]);return{messageId:row.id,status:shouldAdvanceStatus(row.status,next)?next:row.status};}
 async fail(receipt,error){const code=String(error?.code||'META_WEBHOOK_PROCESSING_FAILED').slice(0,120);await this.pool.query(`UPDATE webhook_receipts SET status=CASE WHEN attempt_count>=5 THEN 'dead_letter' ELSE 'failed' END,error=$2,next_attempt_at=clock_timestamp()+(LEAST(300,POWER(2,attempt_count))::text||' seconds')::interval WHERE id=$1`,[receipt.id,code]);}
}
module.exports={MetaWebhookRepository,MetaWebhookError,messageType,messageBody,occurredAt,shouldAdvanceStatus};
