const crypto = require("node:crypto");
function safeStateEqual(actual,expected){const a=Buffer.from(String(actual||""));const b=Buffer.from(String(expected||""));return a.length===b.length&&a.length>=32&&crypto.timingSafeEqual(a,b);}
function createMetaSignupHandlers({store,signupService,connectionRepository,now=()=>Date.now(),ttlMs=10*60*1000}){
  if(!store||!signupService||!connectionRepository)throw new TypeError("Meta signup dependencies are required");
  async function start(req,res){const workspaceId=String(req.body.workspaceId||"");const label=String(req.body.label||"").trim();if(!workspaceId||label.length<2||!store.canManageWorkspace(req.user,workspaceId))return res.status(404).json({error:"Workspace not found"});const state=crypto.randomBytes(32).toString("base64url");const expiresAt=now()+ttlMs;req.session.metaSignup={state,workspaceId,label,expiresAt};return res.status(201).json({state,expiresAt:new Date(expiresAt).toISOString()});}
  async function complete(req,res){const pending=req.session.metaSignup;delete req.session.metaSignup;if(!pending||pending.expiresAt<=now()||!safeStateEqual(req.body.state,pending.state))return res.status(409).json({error:"Meta signup session is invalid or expired",code:"META_SIGNUP_STATE_INVALID"});if(!store.canManageWorkspace(req.user,pending.workspaceId))return res.status(404).json({error:"Workspace not found"});try{const verified=await signupService.exchangeAndVerify({code:req.body.code,businessAccountId:req.body.businessAccountId,phoneNumberId:req.body.phoneNumberId});if(!verified.displayPhoneNumber)return res.status(422).json({error:"Meta did not return a display phone number",code:"META_DISPLAY_PHONE_MISSING"});const installed=await connectionRepository.install({workspaceId:pending.workspaceId,label:pending.label,phone:verified.displayPhoneNumber,phoneNumberId:verified.phoneNumberId,businessAccountId:verified.businessAccountId,accessToken:verified.accessToken});await store.addAudit(req.user.id,"meta.connection.installed",{workspaceId:pending.workspaceId,connectionId:installed.connection.id,numberId:installed.number.id});return res.status(201).json(installed);}catch(error){return res.status(Number(error.status)||422).json({error:error.message,code:error.code||"META_SIGNUP_FAILED"});}}
  return{start,complete};
}
module.exports={createMetaSignupHandlers,safeStateEqual};
