const crypto=require("node:crypto");
class GenericApiRepository{constructor(pool,{perMinute=120}={}){this.pool=pool;this.perMinute=perMinute;}hash(value){return crypto.createHash("sha256").update(value).digest("hex");}
  async createKey(workspaceId,label,scopes){const id=crypto.randomUUID(),secret=`wah_${crypto.randomBytes(32).toString("base64url")}`,prefix=secret.slice(0,12);await this.pool.query("INSERT INTO generic_api_keys(id,workspace_id,label,key_prefix,key_hash,scopes) VALUES($1,$2,$3,$4,$5,$6)",[id,workspaceId,label,prefix,this.hash(secret),scopes]);return{id,workspaceId,label,prefix,scopes,key:secret};}
  async listKeys(workspaceIds){const r=await this.pool.query("SELECT id,workspace_id,label,key_prefix,scopes,active,last_used_at,created_at,revoked_at FROM generic_api_keys WHERE workspace_id=ANY($1::text[]) ORDER BY created_at DESC",[workspaceIds.length?workspaceIds:["__none__"]]);return r.rows;}
  async revoke(workspaceIds,id){const r=await this.pool.query("UPDATE generic_api_keys SET active=false,revoked_at=now() WHERE id=$1 AND workspace_id=ANY($2::text[]) RETURNING id",[id,workspaceIds.length?workspaceIds:["__none__"]]);return Boolean(r.rowCount);}
  async authenticate(secret){if(!secret?.startsWith("wah_"))return null;const r=await this.pool.query("SELECT * FROM generic_api_keys WHERE key_hash=$1 AND active=true",[this.hash(secret)]);if(!r.rowCount)return null;const key=r.rows[0];const usage=await this.pool.query(`INSERT INTO generic_api_usage(api_key_id,minute_bucket,request_count) VALUES($1,date_trunc('minute',now()),1) ON CONFLICT(api_key_id,minute_bucket) DO UPDATE SET request_count=generic_api_usage.request_count+1 RETURNING request_count`,[key.id]);if(usage.rows[0].request_count>this.perMinute)throw Object.assign(new Error("API rate limit exceeded"),{status:429});await this.pool.query("UPDATE generic_api_keys SET last_used_at=now() WHERE id=$1",[key.id]);return key;}
  async existingIdempotency(apiKeyId,key,body){if(!key)return null;const r=await this.pool.query("SELECT request_hash,response FROM generic_idempotency WHERE api_key_id=$1 AND idempotency_key=$2",[apiKeyId,key]);if(!r.rowCount)return null;const hash=this.hash(JSON.stringify(body));if(r.rows[0].request_hash!==hash)throw Object.assign(new Error("Idempotency key was reused with a different request"),{status:409});return r.rows[0].response;}
  async saveIdempotency(apiKeyId,key,body,response){if(!key)return;await this.pool.query("INSERT INTO generic_idempotency(api_key_id,idempotency_key,request_hash,response) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING",[apiKeyId,key,this.hash(JSON.stringify(body)),response]);}
}
module.exports={GenericApiRepository};
